### ISSUE TITLE
i have done every thing as what mentiones but none of them help me to send message

### ISSUE THREAD

**Issue by rdev06** [farhadi/node-smpp#104]
my code for server is:
```node
var smpp = require('smpp');

function checkAsyncUserPass(id,pass,cb){
	if (id == 'admin' && pass == 'admin') {
		cb(0)
	} else {
		cb(1)
	}
}


var server = smpp.createServer(function(session) {
	session.on('bind_transceiver', function(pdu) {
		// we pause the session to prevent further incoming pdu events,
		// untill we authorize the session with some async operation.
		session.pause();
		checkAsyncUserPass(pdu.system_id, pdu.password, function(err) {
			if (err) {
				session.send(pdu.response({
					command_status: smpp.ESME_RBINDFAIL
				}));
				session.close();
				return;
			}
			session.send(pdu.response());
			session.resume();
		});
	});
	session.on('submit_sm',(pdu)=>{
		session.send(pdu.response({
			message_id: '21'
		}));
	});
});
server.listen(2775,()=>console.log('server is running on 2775'));
```

code for session
```node
var smpp = require('smpp');
var session = smpp.connect('smpp://localhost:2775');
session.bind_transceiver({
    system_id: 'roshan',
    password: 'ostindev'
}, (pdu)=> {
    if (pdu.command_status == 0) {
        console.log('bounded');
        // Successfully bound


        session.submit_sm({
            source_addr: 'TEST',
            destination_addr: '+91XXXXXXXXXX',
            message_payload: 'Hi this is test message',
            source_addr_ton: 5,
            source_addr_npi: 1,
            dest_addr_ton: 1,
            dest_addr_npi: 1,
        }, pdu => {
            if (pdu.command_status == 0) {
                console.log(pdu.message_id);
            }
        });
    };
});
```

sim is gsm and i get message on console that i got bounded;
everythingh shows good but i didn't receive any message on my device

**Comment by juliangut** [comment]
Hi @rdev06 I've updated your comment to properly display code blocks

This library is meant to create am SMPP server or SMPP clients to connect to another servers, not for "actually" sending the messages to the devices

For that task you have to get your SMPP client as you did connected to a working SMSC, there are many services around to which you can connect through SMPPP

**Comment by rdev06** [comment]
hi @juliangut I have read your comment and get to know that I can't send message via this library and this library is only meant to manage the sms request(Please correct me if i am wrong).
Again could you please help me to send real message to device by creating my own server (or i need to register for a service somewhere... to get the service).However I want to make one such server for myself to send message to the device.

**Comment by juliangut** [comment]
You got it right @rdev06 you should register in an online SMPP supported service in order to send sms to devices, remember sms are not for free

Depending on the country you are and the country you want to send sms to you can register in many different services such as the one I work for (Instasent)

Reusing your previous **client** code here an example identifying what info is necessary from provider:

```node
// All this information is provided by the service you register on
var providerHost = 'x.x.x.x';
var providerPort = '2775';
var providerSystemId: 'xxxxx';
var providerPassword = 'yyyyy';

var smpp = require('smpp');
var session = smpp.connect('smpp://' + providerHost + ':' + providerPort);
session.bind_transceiver({
    system_id: providerSystemId,
    password: providerPassword
}, (pdu) => {
    if (pdu.command_status == 0) {
        console.log('successful bound');
        session.submit_sm({
            source_addr: 'TEST',
            destination_addr: '+91XXXXXXXXXX',
            message_payload: 'Hi this is test message',
            source_addr_ton: 5,
            source_addr_npi: 1,
            dest_addr_ton: 1,
            dest_addr_npi: 1,
        }, pdu => {
            if (pdu.command_status == 0) {
                console.log(pdu.message_id);
            }
        });
    };
});
```

If what you want is a **server** receiving SMPP messages and just being able to send them to devices you need to connect within your server into another SMSC (mostly the same code as above) to **redeliver** the PDUs you receive

```node
var server = smpp.createServer(function(session) {
	session.on('bind_transceiver', function(pdu) {
		session.pause();
		checkAsyncUserPass(pdu.system_id, pdu.password, function(err) {
			if (err) {
				session.send(pdu.response({
					command_status: smpp.ESME_RBINDFAIL
				}));
				session.close();
				return;
			}
			session.send(pdu.response());
			session.resume();
		});
	});
	session.on('submit_sm',(pdu) => {

        // #########################
        // Redeliver PDU to provider
        // #########################

		session.send(pdu.response({
			message_id: '21'
		}));
	});
});
```

**Comment by juliangut** [comment]
I assume there is no need for more information and this issue should be closed

**Comment by vinodmap** [comment]
Hi @juliangut / @farhadi ,  I realize this is probably a dumb question, but since SMS's are not for free and if I have to use a paid outside service for the SMSC anyway, in what circumstances would I want to use this SMPP server ?  I got the binding to work, but like @rdev06, it's not sending the message (and I understand why given the above posts).  It seems like I should just have my client connect directly with an SMSC server instead of going through this SMPP middleman (server).  Is the SMPP middleman for purposes of keeping track of what SMS's are being sent through the application I'm using and if I don't need to track this information, is there any purpose for going through this SMPP server?  Thank you very much, I really appreciate the information and service.

**Comment by juliangut** [comment]
Hi @vinodmap

The main usage for the server side is to act as an intermediary between clients and any number of possible providers. Imagine those providers could be doing just the same thing

But certainly, in the end if your do not see the server side of this library fitting into your needs then you should only focus on the client side usage, simply bind to an SMSC and start sending your messages

**Comment by vinodmap** [comment]
Thank you @juliangut .  I see -- there could be multiple SMSC servers/providers that may have different pricing for different service areas, in which case we may want to use an SMPP intermediary to route to the correct SMSC server depending on phone geographic origin (or other reasons).  Thanks for this explanation.  The SMSC would likely be implementing their own form of this SMPP server.  Any idea on how to create my own SMSC server without the need to go to an outside service?

**Comment by juliangut** [comment]
Well, you should definitely get in touch with a telecom company to hook your service into theirs or devise a way to deliver the messages yourself, for instance by using an actual device on your end

This is as far as I can advise on this matter due to lack of experience
