### ISSUE TITLE
UDH object is wrong on the server side

### ISSUE THREAD

**Issue by victorsebrito** [farhadi/node-smpp#107]
I'm using this library as both the client and the server. According to the docs,

> For `short_message` and `message_payload` fields you can specify a buffer or a
string or an object containing `udh` and `message` properties, while **`udh` is a
buffer and `message` is either a string or a buffer.**

When sending a `submit_sm` command from the client project, I'm setting the `short_message` parameter like this:

    {
        destination_addr: '2',
        service_type: 'CMT',
        source_addr: '1',
        short_message: {
            udh: Buffer.from([5, 0, 3, 44, 2, 1]),
            message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis"
        }
    }

Looking at #69, it seems I'm doing it the right way. But it arrives like this on the server:

    {
        [...]
        esm_class: 64
        destination_addr: '2',
        service_type: 'CMT',
        source_addr: '1',
        short_message: {
            udh: [Buffer.from([0, 3, 44, 2, 1])],
            message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis"
        }
    }

The `esm_class` parameter has been correctly set, but the `short_message.udh` object is now an array with one object which lost its first piece (the UDH size). Therefore this object is not following the library documentation.

This seems to be an issue with the `udhCoder.getUdh` function. I'm not completely familiar with the SMPP protocol, so I'm not confident enough to submit a pull request with a fix since I don't even know why this function would ever return an array instead of the actual UDH object (including the first piece).

Anyway, if I were to use the PDU object in the client the way it arrived in the server (UDH being an array) to send a new `submit_sm` command, I would get an error:

    TypeError [ERR_INVALID_ARG_TYPE]: The "list[0]" argument must be one of type Array, Buffer, or Uint8Array. Received type object
        at Object.concat (buffer.js:480:13)
        at PDU.encode (c:\Users\Victor\Documents\GitHub\smpp-test\node_modules\smpp\lib\defs.js:545:17)
        at PDU._filter (c:\Users\Victor\Documents\GitHub\smpp-test\node_modules\smpp\lib\pdu.js:135:41)
        at PDU.toBuffer (c:\Users\Victor\Documents\GitHub\smpp-test\node_modules\smpp\lib\pdu.js:166:7)
        at Session.send (c:\Users\Victor\Documents\GitHub\smpp-test\node_modules\smpp\lib\smpp.js:97:24)
        at Session.<anonymous> (c:\Users\Victor\Documents\GitHub\smpp-test\index.js:36:16)
        at Session.emit (events.js:198:13)
        at Session._extractPDUs (c:\Users\Victor\Documents\GitHub\smpp-test\node_modules\smpp\lib\smpp.js:66:8)
        at Socket.emit (events.js:198:13)
        at emitReadable_ (_stream_readable.js:539:12)

**Comment by juliangut** [comment]
Hi @victorsebrito 

There was a recient update to UDH handling _when receiving messages_ in order to support GSM Language Shift Tables, basically to achieve the goal UDH headers needed to be traversed and now they are returned as an array of UDH headers (buffers) **without** the total length of the UDH headers

All the information is in this PR: https://github.com/farhadi/node-smpp/pull/100

**Comment by juliangut** [comment]
Closing as resolved and no feedback received
