### ISSUE TITLE
Node SMPP Server For Multiple Users

### ISSUE THREAD

**Issue by india-india** [farhadi/node-smpp#112]
node js work at single thread so how we can make nodejs smpp server for multiple users.

at present What happen when no. of users send sms so node js is not able to process multiple request .Would u plz help us in this situation

**Comment by juliangut** [comment]
node-smpp supports multiple users by opening sockets to them even though it runs in single thread

node-smpp waits on each socket until receiving a message to be processed (on receiver or transceiver) or until you trigger a send (on transmitter/transceiver)

If you follow the example on server creation it will handle multiple user connections by default

Anyway please attach a node backtrace on your errors

**Comment by juliangut** [comment]
Closing, feel free to reopen providing some error information
