### ISSUE TITLE
smpp client dlr submission

### ISSUE THREAD

**Issue by india-india** [farhadi/node-smpp#115]
suppose a client lost the connection from smpp server and  we have to push dlr to that client when he will reconnected to smpp server 

so how we can push dlr to that client 
plz answere me....

**Comment by juliangut** [comment]
Hello

I'd suggest you keep those dlr on a queue so that you can send them as soon as the client reconnects

**Comment by juliangut** [comment]
Seems no further support is needed, reopen otherwise
