### ISSUE TITLE
Need help for send deliver_sm with node-smpp

### ISSUE THREAD

**Issue by chemax** [farhadi/node-smpp#116]
Hi. I'm dont understand, how i can send deliver_sm when i recieve sms?

**Comment by chemax** [comment]
I was tried it like there https://stackoverflow.com/questions/10137051/how-to-send-deliver-sm-request-add-user-message-reference-tlv-from-node-js-smpp
but in jasmine server I have message status unkown.
` session.deliver_sm({
                    source_addr: pdu.source_addr,
                    destination_addr: pdu.destination_addr,
                    short_message: pdu.short_message,
                    receipted_message_id: msgid,
                    state: 'DELIVRD'
                    // user_message_reference: msgid
                });`

**Comment by juliangut** [comment]
Extending on README file example

```node
const smpp = require('smpp');

const server = smpp.createServer(function(session) {
	session.on('bind_transceiver', function(pdu) {
		// we pause the session to prevent further incoming pdu events,
		// untill we authorize the session with some async operation.
		session.pause();
		checkAsyncUserPass(pdu.system_id, pdu.password, function(err) {
			if (err) {
				session.send(pdu.response({
					command_status: smpp.ESME_RBINDFAIL
				}));
				session.close();
				return;
			}
			session.send(pdu.response());
			session.resume();
		});

		// extract delivery reports from wherever they are, e.g. a message queue
		queue.on('message', function(message) {
			session.send(new smpp.PDU('deliver_sm', {
				esm_class: 4,
				short_message: message.text,
				source_addr: message.destination,
				destination_addr: message.source
			}));
		});
	});
});
server.listen(2775);
```

**Comment by juliangut** [comment]
You have to separate two concepts: receipt sms "confirmation" from deliver_sm

The `submit_sm` ack command is a `submit_sm_resp` (which you have written here: https://gist.github.com/chemax/b9f5c1f64049b6775f191bf3d93d1bb1#file-app-js-L34)
`deliver_sm` is a "new communication" giving information about the status of the sent message

That said, verify that you're receiving `submit_sm` PDU here (https://gist.github.com/chemax/b9f5c1f64049b6775f191bf3d93d1bb1#file-app-js-L30) and review my example for `deliver_sm` PDU payload

**Comment by juliangut** [comment]
Was the information of any help @chemax ?

**Comment by chemax** [comment]
Hi. I'm use another module, who can generate deliver_sm automatically. Thank you for your help.

**Comment by jcdiazhint** [comment]
Hello Chemax, I have the same issue, could you help me please? Which module are using you to deliver DLR?
Thanks in advance.

**Comment by tomas-bethens** [comment]
Hello, I found the way how to send deliver_sm!

```
	var Buffer = require('safer-buffer').Buffer;

	session.on('submit_sm', function (pdu) {
        console.log(pdu.short_message.message);
        let msgid = Date.now().toString(); // generate a message_id for this message.
        try {
            session.send(pdu.response({
                message_id: msgid
            }), (...d) => {
                // console.log('pdu response callback', d)
            });
        } catch (e) {
            console.log(e) 
        }

        const buf = Buffer.from(`id:${msgid} sub:000 dlvrd:000 submitdate:${Math.floor(new Date().getTime()/1000.0)} donedate:${Math.floor(new Date().getTime()/1000.0)} stat:DELIVRD err:4 text:`, 'utf8');
        var deliver_sm = {
            service_type: '',
            source_addr_ton: 1,
            source_addr_npi: 1,
            source_addr: pdu.source_addr,
            dest_addr_ton: 1,
            dest_addr_npi: 1,
            destination_addr: pdu.destination_addr,
            esm_class: 64,
            protocol_id: 0,
            priority_flag: 0,
            schedule_delivery_time: '',
            validity_period: '',
            registered_delivery: 0,
            replace_if_present_flag: 0,
            data_coding: 1,
            sm_default_msg_id: 1,
            short_message: {
                udh: new Uint8Array(buf),
                message: 'short_message'
            }
        };
        var pdu = new smpp.PDU('deliver_sm', deliver_sm);    
        session.send(pdu);  
    });	
```

**Comment by 0LEG0** [comment]
Hello Tomas.
> ```
>         const buf = Buffer.from(`id:${msgid} sub:000 dlvrd:000 submitdate:${Math.floor(new Date().getTime()/1000.0)} donedate:${Math.floor(new Date().getTime()/1000.0)} stat:DELIVRD err:4 text:`, 'utf8');
>         var deliver_sm = {
>             service_type: '',
>             source_addr_ton: 1,
>             source_addr_npi: 1,
>             source_addr: pdu.source_addr,
>             dest_addr_ton: 1,
>             dest_addr_npi: 1,
>             destination_addr: pdu.destination_addr,
>             esm_class: 64,
>             protocol_id: 0,
>             priority_flag: 0,
>             schedule_delivery_time: '',
>             validity_period: '',
>             registered_delivery: 0,
>             replace_if_present_flag: 0,
>             data_coding: 1,
>             sm_default_msg_id: 1,
>             short_message: {
>                 udh: new Uint8Array(buf),
>                 message: 'short_message'
>             }
>         };
>         var pdu = new smpp.PDU('deliver_sm', deliver_sm);    
>         session.send(pdu);  
>     });	
> ```
Here are some fixes for your DLR message:
const { format } = require("fecha");
...
registered_delivery: 1,
short_message: `id:${msgid} sub:000 dlvrd:000 submit date:${format(new Date(), 'YYMMDDHHmm'} done date:${format(new Date(), 'YYMMDDHHmm'} stat:DELIVRD err:4`

Best regards
