### ISSUE TITLE
Randomly freezing without errors

### ISSUE THREAD

**Issue by Ciao121** [farhadi/node-smpp#119]
Hi, 
I have a script that randomly freezes and no error is shown. It happens after few second or one minute.

If, while the script is correctly running I execute: 
> netstat -na |find "2775"
it shows me the connection:
> TCP    192.168.1.43:58676     XXX.XXX.XXX.XXX36:2775    ESTABLISHED
but the same command when the script freezes shows me no connection or sometimes shows me:
>TCP    192.168.1.43:56959     35.177.141.136:2775    CLOSE_WAIT 
and CLOSE_WAIT tatu slast until I force close te nodejs script.
Maybe the server disconnects me for I reason I do not know. The problem is I'm not able to detect this in node so the app stays here doing nothing.

The script load  5.000 messages from a mysql db and start submitting to SPMM server.
When a delivery notification is received it just increase a counter.
Every 1000 sent or received PDU it shows a message. At the end it loops again.

I'm on a Windows machine with node v10.16.0.
Here's the script:

> process.on('uncaughtException', function(err) {
> 	console.error(err.stack);
> 	console.log("Node NOT Exiting...");
> });
> 
> process.on('unhandledRejection', function(err) {
> 	console.error(err.stack);
> 	console.log("Node NOT Exiting...");
> });
> 
> var smpp = require('smpp');
> var mysql = require('mysql');
> 
> var pool = mysql.createPool({
> 	connectionLimit: 10,
> 	host: 'localhost',
> 	user: 'root',
> 	password: '',
> 	database: 'router'
> });
> var counter = 0;
> var maxCount = 3;
> var timeout = 20000; // 20 seconds
> var limit = 5000
> 
> var deliveryCounter = 0
> var session = smpp.connect('smpp://smppserver.ext:2775');
> connect()
> function connect(){
> 	session.bind_transceiver({
> 		system_id: 'test',
> 		password: 'test'
> 	}, function(pdu) {
> 		console.log(pdu)
> 		if (pdu.command_status == 0) {
> 			console.log('Connected')
> 			enquireLink()
> 			getmessages()
> 		}
> 	});
> 
> 
> 
> }
> 
> function enquireLink() {
>     if (counter < maxCount) {
>         session.enquire_link();
>         counter++;
>         console.log('Enquired a link');
> 
>         setTimeout(function () {
>             enquireLink();
>         }, timeout);
>     } else {
>         console.log('The SMPP connection is dead.');
>         session.close();
>         process.exit();
>     }
> }
> 
> session.on('close', function () {
>      console.log('SMPP connection is closed');
>      process.exit();
> });
> 
> session.on('error', function (error) {
>      console.log('SMPP connection error: ' + error);
>      session.close();
>      process.exit(1);
> });
> 
> session.on('enquire_link', function (pdu) {
>      session.send(pdu.response());
>      console.log('Responded an enquire link');
> });
> 
> session.on('enquire_link_resp', function (pdu) {
>      counter = 0;
>      console.log('Received a response to an enquire link');
> });
> 
> 
> session.on('unknown', function(had_err) {
> 	console.log('Session unknown')
>     setTimeout(() => {
>        // session.connect();
>        // session.resume();
>     }, 1000);
> });
> 
> session.on('unbind', function(pdu) {
>      session.send(pdu.response());
>      console.log('SMPP unbind');
>      session.close();
>      process.exit();
> });
> 
> 
> session.on('deliver_sm', function(pdu) {
> 	//console.log(session)
> 	if (pdu.esm_class == 4) {
> 		deliveryCounter++
> 		if (deliveryCounter % 1000 === 0){
> 			console.log('Received notifications ' + deliveryCounter)
> 		}
> 	} else {
> 		console.log('deliver_sm ERROR')
> 	}
> });
> 
> 
> 
> function getmessages() {
> 		getMessages = 'SELECT * FROM messages WHERE status = -1 LIMIT '+limit
> 		pool.query(getMessages, function(error, results, fields) {
> 			if (error) {
> 				if (error.errno == 'ECONNREFUSED') {
> 					console.log("Can't connecto to DB")
> 				} else {
> 					console.log(error.errno)
> 				}
> 			} else {
> 				if (results.length > 0) {
> 					for (var i = 0; i < results.length; i++) {
> 						sendSms(results[i].recipient, results[i].text, results[i].id)
> 					}
> 				} else {
> 					console.log("No messages in queue")
> 				}
> 			}
> 		})
> }
> 
> function sendSms(recipient, text, id) {
> 	session.submit_sm({
> 		destination_addr: recipient,
> 		short_message: text
> 	}, function(pdu) {
> 		if (pdu.command_status == 0) {
> 			if (id % 1000 === 0)
> 			{
> 				console.log("Sent: " + id)
> 			}
> 			if (id === limit)
> 			{
> 				getmessages()
> 			}
> 		} else {
> 			console.log("submit_sm ERROR")
> 		}
> 	});
> }
> 
> 
Any Idea how I can solve this?

**Comment by Ciao121** [comment]
Investigating I get

> 1751	18.078641	192.168.1.43	35.177.141.136	TCP	54	[TCP ZeroWindow] 56116 → 2775 [ACK] Seq=901949 Ack=613203 Win=0 Len=0

on Wireshark sniffing. I tried to limit sms snding to 50/sec but the problem is still there (after some minutes).

**Comment by juliangut** [comment]
I format your code here so it's more readable:

```js
process.on('uncaughtException', function(err) {
    console.error(err.stack);
    console.log("Node NOT Exiting...");
});

process.on('unhandledRejection', function(err) {
    console.error(err.stack);
    console.log("Node NOT Exiting...");
});

var smpp = require('smpp');
var mysql = require('mysql');

var pool = mysql.createPool({
    connectionLimit: 10,
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'router'
});
var counter = 0;
var maxCount = 3;
var timeout = 20000; // 20 seconds
var limit = 5000

var deliveryCounter = 0
var session = smpp.connect('smpp://smppserver.ext:2775');
connect()

function connect() {
    session.bind_transceiver({
        system_id: 'test',
        password: 'test'
    }, function(pdu) {
        console.log(pdu)
        if (pdu.command_status == 0) {
            console.log('Connected')
            enquireLink()
            getmessages()
        }
    });
}

function enquireLink() {
    if (counter < maxCount) {
        session.enquire_link();
        counter++;
        console.log('Enquired a link');

        setTimeout(function() {
            enquireLink();
        }, timeout);
    } else {
        console.log('The SMPP connection is dead.');
        session.close();
        process.exit();
    }
}

session.on('close', function() {
    console.log('SMPP connection is closed');
    process.exit();
});

session.on('error', function(error) {
    console.log('SMPP connection error: ' + error);
    session.close();
    process.exit(1);
});

session.on('enquire_link', function(pdu) {
    session.send(pdu.response());
    console.log('Responded an enquire link');
});

session.on('enquire_link_resp', function(pdu) {
    counter = 0;
    console.log('Received a response to an enquire link');
});

session.on('unknown', function(had_err) {
    console.log('Session unknown')
    setTimeout(() => {
        // session.connect();
        // session.resume();
    }, 1000);
});

session.on('unbind', function(pdu) {
    session.send(pdu.response());
    console.log('SMPP unbind');
    session.close();
    process.exit();
});

session.on('deliver_sm', function(pdu) {
    //console.log(session)
    if (pdu.esm_class == 4) {
        deliveryCounter++
        if (deliveryCounter % 1000 === 0) {
            console.log('Received notifications ' + deliveryCounter)
        }
    } else {
        console.log('deliver_sm ERROR')
    }
});

function getmessages() {
    getMessages = 'SELECT * FROM messages WHERE status = -1 LIMIT ' + limit
    pool.query(getMessages, function(error, results, fields) {
        if (error) {
            if (error.errno == 'ECONNREFUSED') {
                console.log("Can't connecto to DB")
            } else {
                console.log(error.errno)
            }
        } else {
            if (results.length > 0) {
                for (var i = 0; i < results.length; i++) {
                    sendSms(results[i].recipient, results[i].text, results[i].id)
                }
            } else {
                console.log("No messages in queue")
            }
        }
    })
}

function sendSms(recipient, text, id) {
    session.submit_sm({
        destination_addr: recipient,
        short_message: text
    }, function(pdu) {
        if (pdu.command_status == 0) {
            if (id % 1000 === 0) {
                console.log("Sent: " + id)
            }
            if (id === limit) {
                getmessages()
            }
        } else {
            console.log("submit_sm ERROR")
        }
    });
}```

For starters I'd say you have a problem in enquireLink function. Once it reaches maxCount (3) it closes the session and exits the application, that will occur after 1 minute (3 x 20 seconds)

**Comment by Ciao121** [comment]
Thank you for you answer. That's not the problem (I tried to remove that code).

**Comment by ritmas** [comment]
I agree with @juliangut.
@Ciao121 do you have any log with timestamps to share? I'm referring to `console.log()` usage.

If SMPP server doesn't send `enquire_link` event periodically, your SMPP client should do that. Now you're doing it depending on counter sequence - change it so it would run time-wise periodically, e.g.:
```javascript
function enquireLink() {
    setInterval(function() {
        console.log('Enquired a link');
        session.enquire_link();
    }, timeout);
}
```

**Comment by Ciao121** [comment]
I think the problem is that I was sending sms without managing a queue. If the server does something like pause() (not processing new requests) and my client continues to send request this cause trouble in tcp/ip.

I am now using a queue manager ad the problem seems gone. Is there a way to know, in the client, when the server fires a pause event?

**Comment by ritmas** [comment]
I'm not aware of such type of event and [official specs](http://farhadi.ir/downloads/smppv50.pdf) doesn't cover it either. On another hand, from my experience, it's possible to implement custom event (not compatible with SMPP), so you should catch network packets and analyze (e.g. Wireshark) once this happens (share if you can).

You may even try this (if you're lucky enough):
```javascript
session.on('pause', function(pdu) {
    console.log('socket paused?', pdu);
});
```

**Comment by juliangut** [comment]
Do you feel like we can close this issue?

**Comment by juliangut** [comment]
I'm closing the issue as it appears solved, feel free to reopen
