### ISSUE TITLE
Storing bind sessions in redis

### ISSUE THREAD

**Issue by modellhr** [farhadi/node-smpp#120]
We are binding with multiple SMPP servers. At the moment here is our approach for using their session.

```
let servers = []
const session = smpp.connect({
    url: `smpp://${ip}:${port}`
  });

let sessionData ={
   id: id ,  // id of smpp vendor
    session
  }
servers.push(sessionData)
```

and when sms request received, we filter the servers array according to smpp vendor and use its session.  
But when we store session either in DB or in redis storage, we no longer able to use the session. 
In this case, here is error message.  

> session.submit_sm is not a function.

So what is the way to store and use sessions?

**Comment by juliangut** [comment]
From your comment I'll assume you're creating SMPP clients, each one opening a session to an SMPP server

Each `smpp.connect` opens a socket connection and keeps it open, once the connection is opened you have to "bind" to the server with one of `bind_transmitter`, `bind_receiver` or `bind_transceiver`

Finally with the bind up you can then send a `session.submit_sm` or any other message

You have a full example on the README file
```
var smpp = require('smpp');
var session = smpp.connect('smpp://example.com:2775');
session.bind_transceiver({
	system_id: 'YOUR_SYSTEM_ID',
	password: 'YOUR_PASSWORD'
}, function(pdu) {
	if (pdu.command_status == 0) {
		// Successfully bound
		session.submit_sm({
			destination_addr: 'DESTINATION NUMBER',
			short_message: 'Hello!'
		}, function(pdu) {
			if (pdu.command_status == 0) {
				// Message successfully sent
				console.log(pdu.message_id);
			}
		});
	}
});
```

Once that said, what I do is keep a different process for each SMPP client I want running, on each process a session is connected, bound and sends submit_sm (retrieved from a queue) and accepts deliver_sm

Hope it helps

**Comment by modellhr** [comment]
thanks @juliangut for quick reply.

In the example you provided, binding and sending sms taking place. What we are doing is, binding at once and then using its session based on provided param for smpp vendor.

In our Node app, we have two API endpoints. One for binding and one for sending sms. 
for binding, here is logic :

`
let servers =[]
function bindTrans(ip,port,system_id,password, id){
  
  const session = smpp.connect({
    url: `smpp://${ip}:${port}`
  });

  let sessionData ={
    id,
    session
  }

  let filtered = servers.map(s => s.id).indexOf(id);
  if(filtered !== -1){
    servers.splice(filtered,1)
    servers.push(sessionData)
  }else{
    servers.push(sessionData)
  }

 
 session.on('connect', async()=>{

  session.bind_transceiver(
      {
          system_id: system_id,
          password: password
      },
      async function (pdu) {
    
          if (pdu.command_status === 0) {


            enquireLink();
         
          } else {
          
            winston.error('command status is: ', pdu.command_status)
            let filtered = servers.map(s => s.id).indexOf(id);
            if(filtered !== -1){
              servers.splice(filtered,1)
             
            }
            
          }
        }
        );
        
      })

      let counter = 0;
   
      session.on('enquire_link', function (pdu) {
           session.send(pdu.response());
           winston.info('Responded an enquire link');
      });
      
  
      session.on('enquire_link_resp', function (pdu) {
           counter = 0;
           winston.info('Received a response to an enquire link');
      });
      
     
      session.on('unbind', function(pdu) {
           session.send(pdu.response());
           winston.info('SMPP unbind');
           session.close();
           process.exit();
      });
      
    
      session.on('error', function (error) {
           winston.error('SMPP connection error: ' + error);
           session.close();
           process.exit(1);
      });
      
  
      session.on('close', function () {
           winston.info('SMPP connection is closed');
           process.exit();
      });
      session.socket.on('close', function(had_err) {
       const set_timer = setTimeout(() => {
            session.connect();
            session.resume();
        }, 1000);
        ()=>{
          return clearTimeout(set_timer)
        }
    });

    let maxCount = 3;  // totall missed enquire link allowed
    var timeout = 20000; // 20 seconds
    function enquireLink() {
        if (counter < maxCount) {
            session.enquire_link();
            counter++;
            // console.log("Enquire a link for : ", session.options.host);
          const timer =  setTimeout(function () {
                enquireLink();
            }, timeout);
            ()=>{
              return  clearTimeout(timer)
            }
        } else {
          let filtered = servers.map(s => s.session.options.host).indexOf(session.options.host);
          if(filtered !== -1){
            servers.splice(filtered,1)
           
          }
            winston.error("Connection is dead");
         
            session.close();
            process.exit();
        }
    }
}
`
so once we have session stored, we provided another api endpoint for sending sms. It used to take id of smpp vendor and based on that id, we get session that was stored in servers array.

`router.post('/', async(req,res)=>{
  const vendor_id = req.body.id;
   const filtered_server = servers.filter(s => s.id === vendor_id)
   if(filtered_server.length){
     let session = filtered_server[0].session;
      session.submit_sm({
          // data for sending sms
      }, function(pdu){
        if(pdu.command_status === 0){
              //sms sent
        }else{

        }
      })
   }
})`

Can u please tell me the way how to keep different process for each SMPP client ? In our scenario we are using one API end point for all. Thanks

**Comment by juliangut** [comment]
I'll answer your last questions first

Normally SMPP servers have a limit on active number of binds, so usually it's not possible to bind on each request if you have a high volume traffic

To answer your main question I gotta say that from my point of view you're mixing two different things, first on your endpoint you're synchronously receiving messages to send, and then handling them to the smpp session which handles messages asynchronously

I'd advice on separating those two concerns, firstly by storing the messages received in your api endpoints somewhere, database, redis, ..., or directly throw them into a message queue. On the side have a process for each vendor which reads from that ddbb, redis, queue, ..., and process the messages asynchronously

If you want to continue on the path you already have I'd advice on verifying that sessions are active prior to call submit_sm, while at the same time logging each time session connects/disconnects/binds/unbinds to see if the connections are stable

**Comment by juliangut** [comment]
@modellhr given you've moved to another topic creating another issue can we close this one?
