### ISSUE TITLE
How Can i Check the Window Size in Node smpp ?

### ISSUE THREAD

**Issue by anildalar** [farhadi/node-smpp#122]
How Can i Check the Window Size in Node smpp ?

We would like to estimate the expected throughput "T" (in sms/sec). 
T = (number of sessions) x  (window size) / ( latency in sec)
for example: T = N x W / L =  5 x 10 / 0.2 = 250 sms/sec

Please Help

**Comment by juliangut** [comment]
Hi @anildalar 

This library only handles the communication part, only the SMPP protocol itself, nor authentication, maximum number of open binds or window size, those are entirely up to you

You have to control those with session events ("on" methods), by checking a ddbb for number of sessions, or redis for throughput

**Comment by anildalar** [comment]
Thank you for your response
