### ISSUE TITLE
How to Send a message with SAR?

### ISSUE THREAD

**Issue by anildalar** [farhadi/node-smpp#124]
Dear Author.
I have found link of node smpp to send sms using udh. But not found any link to show an example how to send sms using SAR.

Kindly Reply

**Comment by juliangut** [comment]
SAR means Segmentation and Reassembly. It's the mechanisms bound to split sms in sending side and rearrange in receiving side

Have a look here: https://smpp.io/concatenated-messages/

So in the end sending messages with UDH headers it's effectively SAR

**Comment by anildalar** [comment]
Ty. For quick response

**Comment by juliangut** [comment]
Glad you found it helpful. Closing this issue
