### ISSUE TITLE
How I can Send Flash SMS Via Node SMPP?

### ISSUE THREAD

**Issue by anildalar** [farhadi/node-smpp#126]
How I can Send Flash SMS( Class 0 Flash messages) Via Node SMPP?

**Comment by juliangut** [comment]
Hi @anildalar 

In my experience flash sms (or class 0) depend heavily on the provider you're sending the message to, ask them what the exact PDU payload should be

**Comment by juliangut** [comment]
As no more specific explanation can be provided I think we can close this issue
