### ISSUE TITLE
TPS Calculation

### ISSUE THREAD

**Issue by modellhr** [farhadi/node-smpp#129]
Hi @juliangut ,
how do u do?
I have read your answer regarding calculating Window Size  [#122](https://github.com/farhadi/node-smpp/issues/122)

Just to make sure if i got it the way you described, here are my understanding:

TPS = Window Size * Number of Sessions / Latency 

**(1) Number of Session:**  As soon as SMSC receive bind_*, we can store the resulting PDU in DB or in Redis and then count how many sessions are binded. (same way in case of any Unbind or Error we can delete that PDU entry from DB) or read directly from session object (session.server._connections)

**(2) Latency :** We record the Time when ESME sends packets to SMSC. And on SMSC side, time when it receives those packets. Pluse the time SMSC responds back to ESME. 

**(3) Window Size:** I've read that max allowed number of unacknowledged operations is Window size in SMPP. Is there a way to calculate it or it is pre-defined?

Kindly guide if there is more suitable way of calculating TPS by using this library.
Thanks

**Comment by juliangut** [comment]
Hi @modellhr 

You got it right on points 1 and 2, in case you don't need to keep fine-grained track of opened binds using _connections is more than enough

SMPP protocol does not specify any window size or max allowed unacknowledged PDUs so it is mainly an implementation decision you should make, whether you want it or not, again using redis for this purpose is a valid solution

sorry for the late response

**Comment by juliangut** [comment]
Feel free to reopen if needed
