### ISSUE TITLE
MMS using node-smpp

### ISSUE THREAD

**Issue by LinuxDevBD** [farhadi/node-smpp#131]
is it possible to send and receive MMS using node-smpp

**Comment by juliangut** [comment]
MMS messages can be achieved by crafting PDU's UDH headers, you can read about the different types of UDH values here: https://en.wikipedia.org/wiki/User_Data_Header (there is an example for a sound)

The most common use for UDH headers is in the concatenation of messages (as the example below), but you can do much more

```js
const udh = Buffer.from([0x05, 0x00, 0x03, __messageId__, __partsCount__, __partNo__]);
```

**Comment by juliangut** [comment]
Feel free to reopen if needed
