### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by sam08sk** [farhadi/node-smpp#132]
Hi,
I was wondering if someone from the team could offer dedicated support against a fee to resolve an issue we're facing. The app seems to reach 100% CPU and clients are disconnected after that. This usually happens with high traffic of SMS.
CPU profiling data points mostly towards Session._extractPDUs We have removed any blocking code but still the problem persists. The code snippet is as follows:

       let server = smpp.createServer((session) => {
			//get session info
			let system_id, bindid;
			let userData = {
				smppData: null,
				userPermInfo: null,
				routeData: null
			};
			let processBind = {}; //this object stays within this core 
			let sharedBind = {}; // this object is shared among all processes
			session.on('bind_transceiver', (pdu) => {
				//authorize the session
				log(`TRx PDU Received on ${process.env.WorkerName}:`, pdu);
				session.pause();
				system_id = pdu.system_id;
				bindid = Math.random().toString(36).substring(3);
				
				smppAuth(pdu.system_id, pdu.password, async (err, userSmppdata) => {
					if (err || userSmppdata==undefined) {
						session.send(pdu.response({
							command_status: smpp.ESME_RBINDFAIL
						}));
						session.destroy();
						log(`BIND FAILED: Invalid Credentials`);
						return;
					}

					userData.smppData = userSmppdata;
					
					//get user permissions and routedata for this bind
					let [userPermInfo, routeData] = await Promise.all([ getUserPermissions(userSmppdata.user_id), getRouteDetails(userSmppdata.route_id) ]) ;
					userData.userPermInfo = userPermInfo;
					userData.routeData = routeData;
					userPermInfo = routeData = null;
					session.send(pdu.response());
					session.resume();
					log(`TRx BIND EXTABLISHED from ${client_ip}: Waiting for incoming PDU on ${process.env.WorkerName}..`);
					
					//---
					processBind = sharedBind = null;
					
				});
			});

			session.on('submit_sm', (pdu) => {
				let sequence_number = pdu.sequence_number;
				let msgid = uuidv1(); //vendor msg id
				//-- start async processessing of PDU
				let userobj = userData;
				
					asyncProcessPdu(pdu, userobj).then( res => {
						if(res.status=='error'){
							session.deliver_sm(res.options);
							log('Some Error occurred: Response PDU sent..');
						}
					});
				
				session.send(pdu.response({
					message_id: msgid,
					sequence_number: sequence_number
				}));
				log(msgid);
			});

			session.on('unbind', (pdu) => {
				session.send(pdu.response());
				log(`SESSION DISCONNECTED`);
				session.destroy();
			});
			
			session.on('enquire_link', (pdu) => {
					session.send(pdu.response());
			});

			session.on('deliver_sm_resp', (pdu) => {
				let result = someTask(pdu.sequence_number, pdu);
				result.then(()=>{
					log('Delivery Acknowledgement saved in Database . . .');
				})
				
			});

		});
		server.listen(2775);

Anything looks suspicious here? I'm open to suggestions.
-Thanks in advance

**Comment by juliangut** [comment]
At first glance I don't see why that piece of code should produce a memory leak

I don't think `_extractPDUs` method is generating the problem but suffering from lack of memory. That method is responsible of creating the PDU from received stream, and is triggered on every single PDU, and thus if memory is exhausted it will definitely fail

I'ld go about profiling `asyncProcessPdu` and `someTask`

**Comment by Ciao121** [comment]
Me too I'm experiencing 100% cpu usage on high traffic sometime. I'm really not so tech to help. Following the thread...

**Comment by sam08sk** [comment]
> At first glance I don't see why that piece of code should produce a memory leak
> 
> I don't think `_extractPDUs` method is generating the problem but suffering from lack of memory. That method is responsible of creating the PDU from received stream, and is triggered on every single PDU, and thus if memory is exhausted it will definitely fail
> 
> I'ld go about profiling `asyncProcessPdu` and `someTask`

We have done that and couldn't find anything. Also sometimes without even any SMS traffic node shoots up 100% CPU. Right before it happens, the logs show a lot of Enquire_link PDUs received. It is very important to us that we resolve this. Could you offer us a thorough look into this? Please connect to us on Skype at "cubelabs.in". This would be huge help for us.

I am attaching an image. This shows in CPU profile when the node is 100%. The function "anonymous" is just a listener to enquire_link as stated below:

     session.on('enquire_link', (pdu) => {
          session.send(pdu.response());
          log(`Enquire link interval called..`);
     });

<img width="1182" alt="Screenshot 2020-05-19 at 6 04 01 PM" src="https://user-images.githubusercontent.com/65501131/82314372-4d8b3b00-99fc-11ea-980a-1467e8d3f638.png">


As you can see in the image, after this the CPU hangs up and we do not understand why. My first question is why are there multiple calls to "log" function under "anonymous" as there is only one call to log function. And another is why after these enquire_link PDUs are received, CPU hangs up. 
This is what it shows in hung up CPU 

<img width="1166" alt="Screenshot 2020-05-19 at 6 16 05 PM" src="https://user-images.githubusercontent.com/65501131/82314736-d1452780-99fc-11ea-9571-cb5dd14cc2bd.png">


I await your feedback.

**Comment by dsologub** [comment]
Hi @sam08sk @Ciao121 
which Node version are you using?

As I faced same issues when migrating from 8 to 10/12
then rollback to 8 and issues gone

**Comment by Ciao121** [comment]
I'm on 13.11.0 (fresh installed)

**Comment by sam08sk** [comment]
Hello everyone, 

Thank you for your input. I am running this on Node 14, however, I have tested it on 10 and 12 with the same results. Going to Node 8 isn't un option, unfortunately. The issue only happens in a lot of traffic. I suspect that this has something to do with our processing so now we are rewriting our script to only store PDUs and will process them later. I am also looking into the source of SMPP lib and node streams have improved quite a lot since initial node release. 

I will keep you all updated on what I find and what I end up doing. 

-Cheers

**Comment by wladimiravila** [comment]
Hi @sam08sk with how many messages per second this happens? could I know your server configuration?

**Comment by sam08sk** [comment]
Hello everyone, my apologies for the absence. This issue happens only when the SMS per second is very high, say more than 100. Also if a single client is connected, up to 500-600 SMS per second no issue occurs. But with multiple clients, Node reaches 100% CPU pretty quickly with decent traffic. I have reduced the issue significantly by removing most of the processing done during submit_sm event. Now I only save the incoming PDU in REDIS and perform all the PDU processing (joining multipart, routing, billing, validation etc.) on a separate core. However, when there is high traffic of incoming SMS and outgoing DLR at the same time, node still crashes once in a while. 

I have tested this on 8-core system with 16G of RAM. Another test ran on 32G RAM/16-core system provided much better results. I am also looking into node-smpp source now to see if I can optimize that using pipelines. I am doing more optimizations and will keep you guys posted on my findings. All inputs are welcome.

-Cheers

**Comment by anildalar** [comment]
Hi @sam08sk I am using node Worker Thread and cluster combination to determine no of cores of cpu. We are creating seperate threads of every client.
Suppose we have 100 smpp clients connected simultaneously system will create 100 Worker threads. All client are connected on their seperate smpp instance. This is how We are Handling Load . Every client is able to send sms at their speed

**Comment by anildalar** [comment]
We are also testing with Redis

**Comment by sam08sk** [comment]
Hello @anildalar we also flirted with the idea of threads per client in the past. However, in our current system we have close to 800 clients. Creating so many threads wasn't good even on 16-core system. We could put a limit on the number of simultaneous client connections and get it working that way. I'll let you know our findings and final implementation.

**Comment by juliangut** [comment]
I think issue #152 and this one are the same. There is a PR to tackle how _extractPDU functions reads from the buffer

@sam08sk, @anildalar, @Ciao121, and everyone else, could you please give the PR a try to see if it solves the problem so we can release a new version?

**Comment by sam08sk** [comment]
@juliangut I confirm that my issues were solved with this modification in the _extractPDUs method. I tested with varying degrees of SMS and DLR traffic which previously caused the Node process to shoot up to 100% CPU, not anymore.

Thank you so much.

-Cheers

**Comment by ayalabs** [comment]
@sam08sk Can you please Log the _extractPDUs Method modification here so that Author @juliangut and @farhadi  can Merge the fix to master branch. 
We also facing the Freezing issue

**Comment by sam08sk** [comment]
Hi @ayalabs 
the changes are in a couple places and exactly the ones mentioned in the #152 The changes are mentioned here, simply follow this link for the changes:

https://github.com/farhadi/node-smpp/pull/153/files

-Cheers
Sam

**Comment by juliangut** [comment]
New release with the fix!
