### ISSUE TITLE
SMPP over SSL

### ISSUE THREAD

**Issue by jordib123** [farhadi/node-smpp#136]
Is there any way to connect to SMPP server over SSL? I tried smpps:// as url but it is not working. I think it is not possible? Can someone please confirm?

Thanks in advance.

**Comment by juliangut** [comment]
For anyone interested

_server_
```js
const options = {
  cert: fs.readFileSync('route-to-tls.crt'),
  key: fs.readFileSync('route-to-tls.key')
};

const server = smpp.createServer(options, function (session) {
  // ...
});

server.listen(3550); // Custom port, other than default 2775
```

_client_
```js
const session = smpp.connect({
  tls: true,
  host: 'host-or-ip',
  port: 3550
});

// ...
```

**Comment by ritmas** [comment]
This could be added to README file.

**Comment by jordib123** [comment]
I simply had to use ssmpp:// instead of smpps:// as the README states, my bad.

``
session = smpp.connect({
        url: 'ssmpp://' + smpp_host + ':' + smpp_port
});
```
