### ISSUE TITLE
udh is in weird format

### ISSUE THREAD

**Issue by serak** [farhadi/node-smpp#139]
i am trying to create an SMPP buffering server for throttling SMS to my ISP and sometimes i receive multipart SMS from banking application server and its tagging udh of the pdu as this "udh: [ <Buffer 00 03 01 02 02> ]," which i cant make any sense of it, fyi i did console.log(pdu);  and my question is how do i identify if the text i received is a multipart or another different message?
```
short_message: {
    udh: [ <Buffer 00 03 01 02 02> ],
    message: 'y  complaint or enquiry, please call 8980'
  }
```

**Comment by juliangut** [comment]
Following this table: https://en.wikipedia.org/wiki/User_Data_Header#UDH_Information_Elements IEI 0 and 8 identify a concatenated message

```js
if (pdu.esm_class === smpp.consts.ESM_CLASS.UDH_INDICATOR) {
  // Mind that multiple UDH headers can arrive, here we read the first one
  const udh = pdu.short_message.udh[0];

  if (udh[0] === 0x00 || udh[0] === 0x08)) {
    // Concatenated message
  }
}
```

Each byte in the buffer represents a value, review the table

**Comment by serak** [comment]
For some reason pdu.esm_class is 72 instead of the value in `smpp.consts.ESM_CLASS.UDH_INDICATOR` any ways i have fixed it by hard coding to 72

```js
if (pdu.esm_class === 72) {
  // Mind that multiple UDH headers can arrive, here we read the first one
  const udh = pdu.short_message.udh[0];

  if (udh[0] === 0x00 || udh[0] === 0x08)) {
    // Concatenated message
  }
}
```

**Comment by juliangut** [comment]
Closing this as it seems resolved
