### ISSUE TITLE
How to bind smpp on Heroku? 

### ISSUE THREAD

**Issue by giuseppeTrovato20** [farhadi/node-smpp#147]
Hi,

I deployed an api-server on Heroku that in local works perfectly, but when it's on Heroku it's doesn't bind the smpp.
I think the reason is that Heroku doesn't provide a static IP.

What can I do to achieve a connection from there? 
I should set up a proxy server with static IP?

If someone has ever done that, can please explain to me how should I proceed?

**Comment by juliangut** [comment]
Hi @giuseppeTrovato20 I'm sorry but I do not have experience with Heroku, but I have a hunch you're correct about networking. In other providers you can assign an static IP to a machine/droplet/pod/instance/etc

Maybe someone else can shed some light

**Comment by peter-vasarhelyi** [comment]
We could easily connect to an SMPP server from Heroku based on my memories. Although some providers require static IP, others are not. If they require you can use a proxy. You cannot run an SMPP server on Heroku.

**Comment by giuseppeTrovato20** [comment]
> 
> 
> We could easily connect to an SMPP server from Heroku based on my memories. Although some providers require static IP, others are not. If they require you can use a proxy. You cannot run an SMPP server on Heroku.

Good to know at least.

**Comment by juliangut** [comment]
Given the problem appears to be a networking issue I'm closing this
