### ISSUE TITLE
ASCII not encoding \ (reverse solidus)

### ISSUE THREAD

**Issue by polsumeet3666** [farhadi/node-smpp#148]
input text: `"\ This is GSM7 char test \"`

ASCII encoded :  `"@ This is GSM7 char test @"`

**Details**
File : `defs.js`
function :` gsm.encode`
line : `316`
`var extCharRegex = new RegExp('[' + extCharsEnc.replace(']', '\\]') + ']', 'g');`

below function is not able return 
**0x1B2F | 27 47 | REVERSE SOLIDUS (BACKSLASH)**

`string = string.replace(extCharRegex, function(match) {
		return '\x1B' + coder.extCharListEnc[match];
	});
`

**Comment by polsumeet3666** [comment]
generated regex is : `[  ^{}\[~\]|€] `
**above regex does not detect \ (reverse solidus)**

/lib/defs.js
by modify the regex to new: ` [  ^{}\\[~\]|€]`

i am able to process \ char
![image](https://user-images.githubusercontent.com/35520546/93590951-0d00f580-f9cd-11ea-89c2-d16db2a791d3.png)

**Comment by juliangut** [comment]
Hi @polsumeet3666 I can't believe anyone detected this, I guess backslash is not that common of a char in an SMS. Please review/test the PR

**Comment by polsumeet3666** [comment]
@juli
