### ISSUE TITLE
Unbind issue, on every 5 minutes if no any message gets send.

### ISSUE THREAD

**Issue by amber-m-o-r-e** [farhadi/node-smpp#150]
Hi,

I have created an instance of SMMP object with the following code-
```
    session = smpp.connect({
        url: `smpp://${config.host}:${config.port}`,
        auto_enquire_link_period: 10000,
    });
```

But if I will not send any SMS for 5 minutes with "session.submit_sm" then I am getting an "unbind" event from the server.

How this can be handle without sending any polling SMS and is this thing that can be handle from the library itself.

**Comment by juliangut** [comment]
Ho @amber-m-o-r-e 

auto_enquire_link_period option configures a periodic enquire_link PDU send to your provider, depending on their requirements you should set a shorter or larger interval, in your example it is set to 10 seconds

I'd advise you to listen on `enquire_link_resp` PDUs to see if your provider is accepting them and if not contact them

**Comment by juliangut** [comment]
@amber-m-o-r-e I've just realized `auto_enquire_link_period` option has not yet been released, it'll be in the next release, meanwhile you can just set an interval

```node
setInterval(function () {
    session.send(new smpp.PDU('enquire_link'));
}, 10000);
```

**Comment by amber-m-o-r-e** [comment]
Thanks Juliangut, it works no unbind anymore. But there is one more thing can we drop TLV attributes from all messages?

**Comment by juliangut** [comment]
Hi @amber-m-o-r-e 

Currently there should be no TLV when you send if you do not include any. If you see some TLVs on PDUs review your code to avoid including them on PDU creation

**Comment by amber-m-o-r-e** [comment]
Thanks @juliangut.
