### ISSUE TITLE
Freezing randomly with no apparent errors

### ISSUE THREAD

**Issue by jonasrodrigeri** [farhadi/node-smpp#152]
We are having problems with the Session.prototype._extractPDUs function of lib node-smpp/lib/smpp.js:65.

In this function when extracting a given pdu, there comes a time when it generates an infinite loop over the same buffer as the function PDU.fromStream = function (stream) { of the lib node-smpp/lib/pdu.js:43 processes.

In the command buffer = stream.read (command_length); of the lib node-smpp/lib/pdu.js:54, returns null and is reprocessed in a loop and ends up processing and the node freezes.

**Comment by ankit-bisht** [comment]
Same here.

**Comment by williammoterle10** [comment]
Hello, does anyone know how to solve this problem?

**Comment by ihusejnovic** [comment]
Can you test this fix https://github.com/farhadi/node-smpp/pull/153?

**Comment by jonasrodrigeri** [comment]
> Can you test this fix #153?

I'm doing tests here with these changes.

**Comment by juliangut** [comment]
@jonasrodrigeri please share the results of your tests so the fix can be included in next release

**Comment by Vinnie881** [comment]
I am having the exact same issue where there is no error sent to the screen or anything, just an immediate freeze.  Any idea when this may make it to the current release?

**Comment by juliangut** [comment]
Hi @Vinnie881 if you could help testing #153, so we can give it the OK, a new release could be ready as soon as this same week

**Comment by williammoterle10** [comment]
We performed some tests during these 4 days and we had no more crashes on our node.

**Comment by williammoterle10** [comment]
> Estou tendo o que parece ser exatamente o mesmo problema, mas não sei como verificar se esta é a causa exata. Acontece ao enviar grande volume e ter uma enxurrada de PDUs chegando. Não há nenhum erro enviado para a tela ou qualquer coisa, apenas um congelamento imediato. Este é provavelmente o culpado? Isso já está acontecendo há um bom tempo.

We use console.log to print variables within the function cited in the problem (PDU.fromStream).

**Comment by jonasrodrigeri** [comment]
> @jonasrodrigeri please share the results of your tests so the fix can be included in next release

Good morning, we worked with the corrected version for 5 days without any problem, this version can be included in the next release.

**Comment by juliangut** [comment]
New release 0.5.0 with the fix
