### ISSUE TITLE
How to establish successfully a connection between the NodeJS-SMPP Server and a Web browser with ???

### ISSUE THREAD

**Issue by chegmarco1989** [farhadi/node-smpp#157]
Hello.

I am trying to open the SMPP Server connection through Chrome Web Browser by typing the URL http://127.0.0.1:2775/. But every time I hit this URL in my Web Browser, I get the error below at the Terminal where I launched the NodeJS-SMPP Server:

> node SMPPSERVER.js
> 
> Error: PDU length was too large (1195725856, maximum is 16384).
>     at Function.PDU.commandLength (C:\laragon\www\node_modules\smpp\lib\pdu.js:50:9)
>     at Session._extractPDUs (C:\laragon\www\node_modules\smpp\lib\smpp.js:75:32)
>     at Socket.emit (events.js:197:13)
>     at emitReadable_ (_stream_readable.js:539:12)
>     at processTicksAndRejections (internal/process/next_tick.js:76:17)
> Emitted 'error' event at:
>     at Session._extractPDUs (C:\laragon\www\node_modules\smpp\lib\smpp.js:84:9)
>     at Socket.emit (events.js:197:13)
>     at emitReadable_ (_stream_readable.js:539:12)
>     at processTicksAndRejections (internal/process/next_tick.js:76:17)

**How then to establish a connection between the NodeJS-SMPP Server and a Web browser without receiving an error of this kind ???**

Thank you for helping him please.

**Comment by valenti1234** [comment]
> Hello.
> 
> I am trying to open the SMPP Server connection through Chrome Web Browser by typing the URL http://127.0.0.1:2775/. But every time I hit this URL in my Web Browser, I get the error below at the Terminal where I launched the NodeJS-SMPP Server:
> 
> > node SMPPSERVER.js
> > Error: PDU length was too large (1195725856, maximum is 16384).
> > at Function.PDU.commandLength (C:\laragon\www\node_modules\smpp\lib\pdu.js:50:9)
> > at Session._extractPDUs (C:\laragon\www\node_modules\smpp\lib\smpp.js:75:32)
> > at Socket.emit (events.js:197:13)
> > at emitReadable_ (_stream_readable.js:539:12)
> > at processTicksAndRejections (internal/process/next_tick.js:76:17)
> > Emitted 'error' event at:
> > at Session._extractPDUs (C:\laragon\www\node_modules\smpp\lib\smpp.js:84:9)
> > at Socket.emit (events.js:197:13)
> > at emitReadable_ (_stream_readable.js:539:12)
> > at processTicksAndRejections (internal/process/next_tick.js:76:17)
> 
> **How then to establish a connection between the NodeJS-SMPP Server and a Web browser without receiving an error of this kind ???**
> 
> Thank you for helping him please.

you can't SMPP protocol it's not web protocol, and if you try to connect from a browser is interpreted as malformed request and give you an error.

**Comment by juliangut** [comment]
I think valenti1234's answer is more than enough
