### ISSUE TITLE
Parameter collision in QuerySM Response

### ISSUE THREAD

**Issue by christo-christoff** [farhadi/node-smpp#158]
**Issue description**
Тhe following exception is thrown when [ _query_sm_resp_ ] is attempted to be sent:

> internal/buffer.js:49
>   throw new ERR_OUT_OF_RANGE(type || 'offset',
>   ^
> 
> RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 48. Received 50
>     at boundsError (internal/buffer.js:49:9)
>     at checkBounds (internal/buffer.js:30:5)
>     at checkInt (internal/buffer.js:37:3)
>     at writeU_Int16BE (internal/buffer.js:649:3)
>     at Buffer.writeUInt16BE (internal/buffer.js:657:10)
>     at /home/christoff/Scripts/NodeJS/SMPP/node_modules/smpp/lib/pdu.js:187:11
>     at Array.forEach (<anonymous>)
>     at PDU.toBuffer (/home/christoff/Scripts/NodeJS/SMPP/node_modules/smpp/lib/pdu.js:186:10)
>     at Session.send (/home/christoff/Scripts/NodeJS/SMPP/node_modules/smpp/lib/smpp.js:97:24)
>     at Session.<anonymous> (/home/christoff/Scripts/NodeJS/SMPP/QuerySMTestServer.js:13:14)

**Analysis**
I have investigated the above issue and I have found that it is caused by a key collision.
The constructor _PDU(command, options)_ and the method _PDU.prototype.toBuffer_ 
from module _pdu.js_ are based on the assumption that mandatory and optional parameter
(TLV) names are unique and both key spaces will not overlap in PDU object.

However, this is not the case with [ _message_state_ ], which exists as a key in both mandatory
and optional parameter (TLV) key spaces and in [ _query_sm_resp_ ] collision occurs. This makes
message_state to be written twice - first as mandatory and than as optional parameter.

**Propsed solution**
Since the only collision I have found for [ _message_state_ ] is in [ _query_sm_resp_ ] one 
possible solution will be a check to be added: _if (this.command == 'query_sm_resp')_ 

**function PDU(command, options)**
```
function PDU(command, options) {
    if (Buffer.isBuffer(command)) {
        return this.fromBuffer(command);
    }
    options = options || {};
    this.command = command;
    this.command_length = 0;
    this.command_id = commands[command].id;
    this.command_status = options.command_status || 0;
    this.sequence_number = options.sequence_number || 0;
    if (this.command_status) {
        return;
    }
    var params = commands[command].params || {};
    for (var key in params) {
        if (key in options) {
            this[key] = options[key];
        } else if ('default' in params[key]) {
            this[key] = params[key].default;
        } else {
            this[key] = params[key].type.default;
        }
    }

    if (this.command == 'query_sm_resp') return;
    // Thus we prevent adding message_state for
    // the second time as optional parameter

    for (var key in options) if (key in tlvs) {
        this[key] = options[key];
    }
}
```
**PDU.prototype.toBuffer**
```
PDU.prototype.toBuffer = function() {
    this.command_length = 16;
    if (this.command_status) {
        return this._initBuffer();
    }
    this._filter('encode');
    var params = commands[this.command].params || {};
    for (var key in this) {
        if (params[key]) {
            this.command_length += params[key].type.size(this[key]);
        } else if (tlvs[key]) {
            var values = tlvs[key].multiple ? this[key] : [this[key]];
            values.forEach(function(value) {
                this.command_length += tlvs[key].type.size(value) + 4;
            }.bind(this));
        }
    }
    var buffer = this._initBuffer();
    var offset = 16;
    for (var key in params) {
        params[key].type.write(this[key], buffer, offset);
        offset += params[key].type.size(this[key]);
    }

    if (this.command == 'query_sm_resp') return buffer;
    // The same approach here
    
    for (var key in this) if (tlvs[key]) {
        var values = tlvs[key].multiple ? this[key] : [this[key]];
        values.forEach(function(value) {
            buffer.writeUInt16BE(tlvs[key].id, offset);
            var length = tlvs[key].type.size(value);
            buffer.writeUInt16BE(length, offset + 2);
            offset += 4;
            tlvs[key].type.write(value, buffer, offset);
            offset += length;
        });
    }
    return buffer;
};
```
Since other, more general solutions probably exist, I would like to ask for your comments.

**Comment by dxhj** [comment]
I'm having the same problem:
`RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 54. Received 56`

My code:
```
    session.on("query_sm", (pdu) => {
      session.send(pdu.response({
        message_id: pdu.message_id,
        message_state: smpp.MESSAGE_STATE.ACCEPTED
      }));
    });
```

**Comment by juliangut** [comment]
> Since the only collision I have found for [ message_state ] is in [ query_sm_resp ] one possible solution will be a check to be added: if (this.command == 'query_sm_resp')

I've checked SMPP protocol thoroughly on mandatory and optional parameters and `message_state` is the only duplicated parameter

* for `query_sm_resp` is an integer between 1 and 8
* for `deliver_sm` and `data_sm` is a 8 octet integer

I'll review what is the best solution, PRs are always wellcome

**Comment by christo-christoff** [comment]
The bug I have found is caused by a name collision of  **message_state** parameter.
It is described twice in SMPP Protocol (3.4 and 5.0):

1. As a mandatory parameter in:
```
query_sm_resp: {
	id: 0x80000003,
	params: {
		message_id: {type: types.cstring},
		final_date: {type: types.cstring, filter: filters.time},
		message_state: {type: types.int8},
		error_code: {type: types.int8}
}
```

2. As an optional parameter (usually sent with Delivery Receipt in _data_sm_ and _deliver_sm_):
```
message_state: {
	id: 0x0427,
	type: types.tlv.int8
}
```

**Offtopic**  _message_state_  is 1 byte long and can contain only the following values according to SMPP 5.0:
```
MESSAGE_STATE: {
	SCHEDULED:     0,
	ENROUTE:       1,
	DELIVERED:     2,
	EXPIRED:       3,
	DELETED:       4,
	UNDELIVERABLE: 5,
	ACCEPTED:      6,
	UNKNOWN:       7,
	REJECTED:      8,
	SKIPPED:       9
}
```

The bug is triggered only in the following functions:

1. In _function PDU(command, options)_ when mandatory and optional parameters are inserted into PDU Object:
```
// 1st time _message_state_ is added as mandatory
	var params = commands[command].params || {};
	for (var key in params) {
		if (key in options) {
			this[key] = options[key];
		} else if ('default' in params[key]) {
			this[key] = params[key].default;
		} else {
			this[key] = params[key].type.default;
		}
	}

// 2nd time _message_state_ is tried to be added as an optional parameter, but
// since the parameter name is the same it is only overwritten without causing any issue
	for (var key in options) if (key in tlvs) {
		this[key] = options[key];
	}
```

2. In _PDU.prototype.toBuffer_ when the Buffer is filled with mandatory and optional parameters from PDU Object:
```
// Here the mandatory parameters are getting added to Buffer (message_state as well):
	for (var key in params) {
		params[key].type.write(this[key], buffer, offset);
		offset += params[key].type.size(this[key]);
	}

// Here is where the Exception is getting thrown, because the function tries to add [ message_state ] 
// INCORRECTLY  for the second time as an optional parameter, but Buffer size is calculated CORRECTLY by chance
// (Since the same parameter gets overwritten, without causing any issue in PDU(command, options)) 
	for (var key in this) if (tlvs[key]) {
		var values = tlvs[key].multiple ? this[key] : [this[key]];
		values.forEach(function(value) {
			buffer.writeUInt16BE(tlvs[key].id, offset);
			var length = tlvs[key].type.size(value);
			buffer.writeUInt16BE(length, offset + 2);
			offset += 4;
			tlvs[key].type.write(value, buffer, offset);
			offset += length;
		});
	}
	return buffer;
```
I have proposed one possible solution to avoid this collision in my previous message:
```
...
    if (this.command == 'query_sm_resp')
...
```

Best Regards,
Christo Christoff

**Comment by juliangut** [comment]
I've created PR #160 with a fix, after reviewing SMPP v5 I've fond that not only query_sm_resp PDU should be controlled for this parameter but query_broadcast_sm_resp as well

Please, review and test the PR

**Comment by christo-christoff** [comment]
Hi Julian,

1. In query_broadcast_sm_resp [message_state] is a mandatory TLV, 
   (no other parameter with the same name) so no collision will occur.

2. Regarding your PR #160:
```
	for (var key in options) {
		if (key in tlvs && (key !== 'message_state' || this.command !== 'query_sm_resp')) {
			this[key] = options[key];
		}
	}
```
I find it not optimal, since:
```
    (key !== 'message_state' || this.command !== 'query_sm_resp')
```
will be checked for EVERY Optional parameter on EVERY SMPP Command.

Best Regards,
Christo Christoff

**Comment by juliangut** [comment]
Hi @christo-christoff 

The PR has been updated to skip any optional parameter with the same name as those mandatory for a given command, simplifying the comparison not needing to compare single commands

```php
for (var key in this) if (tlvs[key] && !(key in params)) {
```

Thanks for reviewing, any comment is wellcome

**Comment by juliangut** [comment]
PR has been merged and will be available in the next release
