### ISSUE TITLE
Command status 69 error while sending SMS 

### ISSUE THREAD

**Issue by sarathsr-olt** [farhadi/node-smpp#159]
Hi Team,
I am using node-smpp for sending SMS. I have 2 accounts. One for marketing SMS and One for transactional SMS. Everything was working fine. I send around 6000 SMS from both accounts at a time. But suddenly I am not able to send SMS through my Transactional account. The promotional account is working fine. Now I am getting the following PDU response if I send SMS through my transactional account.

> PDU {                
>     command_length: 17,  
>     command_id: 2147483652,    
>     command_status: 69,    
>     sequence_number: 3,     
>     command: 'submit_sm_resp',
>     message_id: ''    
> }
Do you guys have any idea what's the issue?.

**Comment by anildalar** [comment]
@sarathsr-olt I can Solve the issue . Plz Contact me on my Whatsapp +91-7999452711

**Comment by modellhr** [comment]
@sarathsr-olt ,  [review this.](https://github.com/farhadi/node-smpp/issues/60)

**Comment by juliangut** [comment]
@sarathsr-olt I'm assuming both connections (marketing and transactional) are implemented the exact same way

I don't know if your provider for both connections is the same or are two different. Given the error is coming in the response to a submit_sm, and ESME_RSUBMITFAIL (69) is just a generic submission failure, I can only assume you're using different providers and the one used for transactional traffic is having some problem

It might be an internal problem on the provider side, but it may be as well a change in the way the expect the messages (npi and ton probably). I'd contact the provider and send them an example of the submit_sm and submit_sm_resp PDUs asking for advice

**Comment by sarathsr-olt** [comment]
@juliangut, @modellhr Thanks for your replies. Yes, it's in fact an issue from the provider side. They had some internal network issues. It's fixed now and everything works smooth now.

**Comment by juliangut** [comment]
Glad to here it, closing the issue
