### ISSUE TITLE
delay when sending submit_sm 

### ISSUE THREAD

**Issue by ghamdannosary** [farhadi/node-smpp#162]
hi every one ,

I note that there is some delay in response when sending sms to smpp server ( node-smpp) , 
any suggestion please ?

**Comment by juliangut** [comment]
Hi @ghamdannosary could you be more specific? have you profiled your application and identified the delay? any part in particular of the code in which it might be happening?

**Comment by juliangut** [comment]
I'm closing this issue as several months have passed with no feedback
