### ISSUE TITLE
Transceiver mode and enquire link

### ISSUE THREAD

**Issue by Ciao121** [farhadi/node-smpp#164]
Hi everyone,
I'm connecting to my provider in tranceiver mode. So I can both send messages and receive delivery reports on the same connection. Every 60 seconds I send an enquire link and I get enquire response back.
Today I started sending messages and receivign DLR but, after few messages I was no more receiving DLRs (I waited more than 10 minutes with no DLR). Messages where going out normally. Enquire responses were ok. I restarted my application and DLRs were back again.
Is it possible that, in transceiver mode, only the receiver part (in my case) goes down? And how can I detect it?
Or any other idea of what could happen?

Thank you!

**Comment by augustolzd** [comment]
Hi Ciao,

If you could put your code here will be easier to help you, but in general, if your connection is up, DLR need to back to you, only when you are completely disconnected you can't receive it

**Comment by juliangut** [comment]
@Ciao121 

With the information you gave I'd say it is not possible to "disconnect" only the receiving side of a transceiver bind while you are keeping it alive with enquire_link PDUs

So I opt for a problem on your provider by which at some point the stop sending you deliver_sm packets and when you reconnect all the pending PDUs are sent at once

**Comment by juliangut** [comment]
Closing as no new information was added in quite some time, feel free to comment otherwise
