### ISSUE TITLE
SMPP Server in cluster mode setup

### ISSUE THREAD

**Issue by fardhana** [farhadi/node-smpp#165]
Hi, i want to start this lib for my own smpp server.
And now i want to trying in cluster mode setup. Can you share how to achieve it?

Does start the server via pm2 cluster mode accomplished it

Thanks

**Comment by juliangut** [comment]
Hi @fardhana you can perfectly use pm2 cluster mode, review pm2 setup

**Comment by anildalar** [comment]
We have successfully developed a smpp plateform using node-smpp , Kafka and
redis. If any one need professional service. We can help.
Thanks & Regards.
https://oklabs.in
OKMESSAGING
AnilDollor

**Comment by juliangut** [comment]
@fardhana I'm closing this issue as I believe it is answered, please reopen if you feel like needing more information
