### ISSUE TITLE
Throughput support

### ISSUE THREAD

**Issue by Julien-ADDREA** [farhadi/node-smpp#167]
Hello, I am working on a SMPP client, I need to implement throughput support so as not to exceed the limit imposed by our provider
How can i do that ?

I saw this but it doesn't help me :
https://github.com/farhadi/node-smpp/issues/122

Thx 🙂

**Comment by telecomsxchange** [comment]
> Hello, I am working on a SMPP client, I need to implement throughput support so as not to exceed the limit imposed by our provider
> 
> How can i do that ?
> 
> 
> 
> I saw this but it doesn't help me :
> 
> https://github.com/farhadi/node-smpp/issues/122
> 
> 
> 
> Thx 🙂

@Julien-ADDREA Check if this script helps you solve the problem. 

https://dev.to/telecomsxchange/nodejs-smpp-stress-tester-with-configurable-parameters-3h9i

**Comment by juliangut** [comment]
@Julien-ADDREA , telecomsxchange solution may be enough depending on your case. For a more complex solution you should have a look at the several throttling/limiting npm packages available

**Comment by juliangut** [comment]
Closing as no new information was added in quite some time
