### ISSUE TITLE
_callbacks should use an object instead of an array

### ISSUE THREAD

**Issue by humaidk2** [farhadi/node-smpp#170]
Hi,

i noticed _callbacks in smpp.js is using an array to store sessions, but deleting elements in an array causes null spaces
I suggest moving it to an object or using .filter or .splice to remove elements from the array

https://github.com/farhadi/node-smpp/blob/fe53dcc6944d6a8b3516c08c51b7c119db3a517c/lib/smpp.js#L17

**Comment by juliangut** [comment]
Hello @humaidk2 

PRs are always welcome, if you find the time to create one would be awesome
