### ISSUE TITLE
no submit_sm response from server (Random Behavior)

### ISSUE THREAD

**Issue by ajamous** [farhadi/node-smpp#173]
I have a case but am I am not sure where it's coming from, SMPP LIB or externally, but thought to share it here in case someone has faced it before or to log a solution if found.

The issue that very randomly and inconsistently, the customer sends multiple submit_sm while many of them receive a submit_sm response some don't at all.  I have verified with tcpdump on both sides that the submit_sm is sent from the client network and arrived at the server. but no submit_sm resp sent back to them, even thought at the same time stamp other messages are logged and processed just fine. What's also strange that I can see the submit_sm in tcpdump but I cannot see it in smpp server logs at all.  So I'm not sure that I have received the submit_sm on the smpp server  or it dropped somewhere in the between. I was not able a way to reproduce this issue (still looking).

i do have a suspicion with isession.pause() and isession.resume()  that we are using for submit_sm authorization, with following code:

```javascript
isession.nickname) 
                 //authorization
 		isession.pause()
                     let authx = await authorizeAccount(isession, pdu)
 		isession.resume()
 		     await uponAuthSubmit(authx, isession, pdu)
 		return
         })

 func (session *sessionSync) send(remoteSm *pdu.SubmitSm, serverSm *pdu.SubmitSm, ctx *smpp.Context) {
 	session.mu.Lock()
 	defer session.mu.Unlock() 
```

not sure if my thought is right but maybe when resume() is called some of the submit_sm are lost?  

Another thing, that at nearly the same time there is a message with the same exact sequence number which receives the submit_sm response. 

For e.g. 

Two different messages (different to_numbers, sender ids) with the same sequence number 2151251, one gets a response and secondly does not. Not sure if this has something to do with it. 

I also run on NodeJS v8.17.0 (due for an upgrade) but I am not sure if the issue is describing may be related to that or to the smpp library itself. 

When we tried to reproduce it with manual testing and even stress testing, it does not show. Also, I have checked server load & smpp server load at that time and it was normal.

**Comment by juliangut** [comment]
Hi @ajamous 

I'm going to review what you comment about _resume_, though I don't see this problem

Appart from that

> Two different messages (different to_numbers, sender ids) with the same sequence number 2151251, one gets a response and secondly does not.

This is sort of correct. You should not send nor receive two PDUs with the same sequence number, at least not in short period of time

Consider sequence_number is used to identify PDU to respond to, this library keeps callback methods identified by sequence_number(https://github.com/farhadi/node-smpp/blob/master/lib/smpp.js#L114), when it receives the response it triggers the callback according to the sequence_number and then discarded (https://github.com/farhadi/node-smpp/blob/master/lib/smpp.js#L92), so if you receive the same sequence_number twice the second time there will be no callback to be triggered

It is not clear to me if you're experiencing this duplicated sequence_number on the sending or receiving part. If on the sending part, sequence_number is kept different on every send over here: https://github.com/farhadi/node-smpp/blob/master/lib/smpp.js#L106

**Comment by ajamous** [comment]
Thanks @polsumeet3666

**Comment by ajamous** [comment]
Yes @juliangut thx
