### ISSUE TITLE
Cannot read property 'length' of undefined when trying to send deliver_sm

### ISSUE THREAD

**Issue by DewZ89** [farhadi/node-smpp#174]
Hi,
I got the following error when trying to send a deliver_sm:
```TypeError: Cannot read property 'length' of undefined```

I send a deliver_sm to appropriate SMPP client when i receive a deliver receipt from an operator HTTP API. 
Each DLR I receive by HTTP is put into a Rabbitmq queue. So when my SMPP server (which consume the queue) receive a new message I try to send a deliver_sm. Below the code:
```javascript
const dlrData = JSON.parse(message.content.toString())
this.session.deliver_sm({
    ...dlrData,
    esm_class: 2,
})
```
with dlrData containing 
```javascript
'short_message': {
       'id': string,
       'sub': number,
       'dlvrd': number,
       'submit_date': string,
       'done_date': string,
       'stat': string,
       'error': number,
       'text': string
},
'source_addr': string,
'destination_addr': string
```

Can you help me to correctly build the deliver_sm command?

**Comment by polsumeet3666** [comment]
inside deliver_sm PDU short message is string type.
please refer to sample dlr below
PDU {
  command_length: 197,
  command_id: 5,
  command_status: 0,
  sequence_number: 1,
  command: 'deliver_sm',
  service_type: '',
  source_addr_ton: 1,
  source_addr_npi: 1,
  source_addr: '+000000000000',
  dest_addr_ton: 5,
  dest_addr_npi: 1,
  destination_addr: '000000',
  esm_class: 4,
  protocol_id: 0,
  priority_flag: 0,
  schedule_delivery_time: '',
  validity_period: '',
  registered_delivery: 0,
  replace_if_present_flag: 0,
  data_coding: 0,
  sm_default_msg_id: 0,
  short_message: {
    message: 'id:100000000000123508 sub:000 dlvrd:000 submit date:210611083615 done date:210611083615 stat:REJECTD err:600 Text:'
  },
  message_state: 5,
  receipted_message_id: '100000000000123508'
}

**Comment by DewZ89** [comment]
Thanks @polsumeet3666. It works now.
I was missing the correct ```short_message``` format.

Thanks again.
