### ISSUE TITLE
Unable to start SMPP Server.

### ISSUE THREAD

**Issue by niteshtripathi1234** [farhadi/node-smpp#176]
import * as _ from 'lodash';
import { config } from '../config';
import * as smpp from 'smpp';
import * as controller from '../controller';
import * as winston from 'winston';
import { IMessage } from 'src/interfaces';
import console = require('console');

const logger = winston.createLogger({
    level: 'info',
    format: winston.format.json(),
    defaultMeta: { service: 'user-service' },
    transports: [
        new winston.transports.File({ filename: 'receive.log' })
    ]
});

export default class SMPP {

    public static async createServer() {
        // const pdu = JSON.parse("{\"command_length\":70,\"command_id\":4,\"command_status\":0,\"sequence_number\":46,\"command\":\"submit_sm\",\"service_type\":\"\",\"source_addr_ton\":1,\"source_addr_npi\":1,\"source_addr\":\"16785223503\",\"dest_addr_ton\":1,\"dest_addr_npi\":1,\"destination_addr\":\"18135137238\",\"esm_class\":0,\"protocol_id\":0,\"priority_flag\":0,\"schedule_delivery_time\":\"\",\"validity_period\":\"\",\"registered_delivery\":0,\"replace_if_present_flag\":0,\"data_coding\":1,\"sm_default_msg_id\":0,\"short_message\":{\"message\":\"Hello received \"}}");
        // console.log(pdu);
        // const message: IMessage = {
        //     from: pdu.source_addr,
        //     to: pdu.destination_addr,
        //     text_content: _.get(pdu, 'short_message.message') + Math.random()
        // };
        // console.log(message);
        // controller.rabbit.sendSMStoRabbit(message);
        const server = smpp.createServer((session) => {
            session.on('bind_transceiver', (pdu) => {
                session.pause();
                if (pdu.system_id === config.system_id && pdu.password === config.password) {
                    session.send(pdu.response());
                    console.log('[Client connected]');
                    session.resume();
                    session.on('submit_sm', (pdu) => {
                        console.log('[PDU]', pdu);
                        logger.log({
                            level: 'info',
                            created: new Date(),
                            message: JSON.stringify(pdu)
                        });
                        const message: IMessage = {
                            from: pdu.source_addr,
                            to: pdu.destination_addr,
                            text_content: _.get(pdu, 'short_message.message')
                        };
                        logger.log({
                            level: 'info',
                            created: new Date(),
                            message: JSON.stringify(message)
                        });
                        controller.rabbit.sendSMStoRabbit(message);
                        session.send(pdu.response());
                    });

                } else {
                    session.send(pdu.response({
                        command_status: smpp.ESME_RBINDFAIL
                    }));
                    session.close();
                    return;
                }
            });

            session.on('close', () => {
                console.log('SMPP client session close');
            });

            session.on('error', (err) => {
                console.log('Client error', err);
            });
        });
        console.log('config.port ', config.port);
        server.listen(config.port);
    }
}

I am getting this error

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'context' of undefined
at Server.getTicketKeys (_tls_wrap.js:936:28)
at Server._getServerData (_tls_wrap.js:925:22)
at EventEmitter.cluster._getServer (internal/cluster/child.js:84:24)
at listenInCluster (net.js:1341:11)
at Server.listen (net.js:1415:7)
at Server.listen (/app/node_modules/smpp/lib/smpp.js:176:37)
at Function.createServer (/app/src/controller/smpp.ts:74:16)
at Object.<anonymous> (/app/src/server.ts:4:17)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by juliangut** [comment]
As per #171 this should be fixed
