### ISSUE TITLE
Query : Can we implement ip whitelist/filter 

### ISSUE THREAD

**Issue by polsumeet3666** [farhadi/node-smpp#177]
@juliangut Sir,
we are using around 50 smpp instance behind load balancer LB
we have a requirement for filtering smpp bind using client's IP.
can you please suggest how we can accomplish this.
Approachs
1.  implement ip white listing on Load balance (traefik level)
2.  implement ip white listing at smpp instance level (if possible)

Thanks in advanced

**Comment by juliangut** [comment]
Hi @polsumeet3666 

I'd suggest you follow the load balancer option if possible

If not possible you can implement an IP filter the same way auth is implemented in the example on the readme file. You can extract IP from the socket: `session.socket.remoteAddress` and check its validity against your data store

**Comment by juliangut** [comment]
Just cleaning issues

Previous comment should answer the issue, feel free to reopen if needed
