### ISSUE TITLE
ASCII/GSM7 encoding conflict

### ISSUE THREAD

**Issue by jordib123** [farhadi/node-smpp#181]
Telecom operator requires GSM7 encoding (if I understand correctly GSM7 = GSM 03.38). The documentation states that ASCII equals GSM 03.38 `This smpp implementation supports 3 encodings: ASCII (GSM 03.38), LATIN1, and UCS2.` However, we are receiving complaints from our telecom operator that they are receiving IA5 (CCITT T.50)/ASCII (ANSI X3.4) instead of GSM7. Are we able to force GSM 03.38? As ASCII = GSM 03.38 (if I understand the documentation correctly) I am not sure what to do?

**Comment by juliangut** [comment]
Hi @jordib123 

Most probably your operator is detecting `data_coding` PDU parameter and complaining about it not being correct

Try forcing `data_coding` parameter in submit_sm to be `0` (default, usually GSM7). The encoding auto-detection is most certainly detecting ASCII and setting the value to 1

Hope it helps

**Comment by juliangut** [comment]
Closing as no further info provided

**Comment by dotsinspace** [comment]
Not working...same issue client is complaining that sms are empty or have some issue with encoding.
