### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by ksabariraj** [farhadi/node-smpp#19]
Hi,

Thanks for the module. I am getting the below error. Please guide me on this.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)

Thanks,
Sabari.

**Comment by daper** [comment]
Can you explain how do you make binding (BIND_* ops)?

**Comment by ksabariraj** [comment]
Hi,

Sorry for the delay response. 

After restarting the system, its seem good. 

But, I have different issue. I am unable to set ID for message. for tracking purpose I tried to Set my unique ID, but, its not working.
 
Thanks for your time.

**Comment by daper** [comment]
Hi @ksabariraj 

I'm not very sure of how you are trying to set ID. Try with different approach; you could save the meesage_id returned by the ack pdu (*_resp), usually submit_sm_resp to perform query, cancel and replace calls.

**Comment by ksabariraj** [comment]
Thanks, I changed the logic and now working good :-)
