### ISSUE TITLE
I can not receive message to my phone number

### ISSUE THREAD

**Issue by aflorom** [farhadi/node-smpp#194]
Hi!

I have testing the sending of message with the example of README.md file with SMPP Session and SMPP server and I can see that receive communication between them but right now I am not receiving any message. I have followed the steps in README.md file and the changed that I have applied is the replacement of the phone number. My phone number is from Spain so I have applied the format +34xxxxxxxxx. Have I missed some configuration or is fine? 

I have tried too to refactor code example to some minimal without function for checking password, so my last tests were with the next configuration:

SMPP server:

```
var smpp = require('smpp');
var server = smpp.createServer({ debug: true })

server.listen(2775);
```

SMPP session:

```
var smpp = require('smpp');
var session = smpp.connect({
  url: 'smpp://localhost:2775',
  auto_enquire_link_period: 10000,
  debug: true
})

session.submit_sm({
  destination_addr: '+34xxxxxxxxx',
  short_message: 'Hello!'
})
```

Thanks!

**Comment by juliangut** [comment]
Hi @aflorom 

Your code is missing steps from the example code:

On your client side code you have to request a bind by sending a bind PDU, `session.bind_transceiver({system_id: 'YOUR_SYSTEM_ID', password: 'YOUR_PASSWORD'}, ...`
And on your server side code you have to wait to receive this PDU and act accordingly `session.on('bind_transceiver', function(pdu) {...`

Only when you have successfully established a binding you should send sumit_sm on the client side and listen to  those submit_sm PDUs on server side

**Comment by aflorom** [comment]
Hi @juliangut

My first comment was wrong but I have been testing with the next code example althougth I was not listening the submit_sm event on server side.

Now I am testing with the identical code from README example.

My client and server figure like the next example:

SMPP server

```
var smpp = require('smpp');

var server = smpp.createServer({
  debug: true
}, function (session) {

  session.on('error', function (err) {
    // empty callback to catch emitted errors to prevent exit due unhandled errors
    if (e.code === "ETIMEOUT") {
      // TIMEOUT
      session.close();
    } else if (e.code === "ECONNREFUSED") {
      // CONNECTION REFUSED
      session.close();
    } else {
      // OTHER ERROR
      session.close();
    }
  });

  session.on('submit_sm', function (pdu) {

    var msgid = Math.floor(Math.random() * 10000000).toString(); // generate a message_id for this message.

    session.send(pdu.response({
      message_id: msgid
    }));
  })

  session.on('bind_transceiver', function (pdu) {
    // pause the session to prevent further incoming pdu events,
    // untill we authorize the session with some async operation.
    session.pause();

    var checkAsyncUserPass = function (user, pwd, onComplete) {
      setTimeout(function () {
        if (user === "YOUR_SYSTEM_ID" && pwd === "YOUR_PASSWORD") {
          onComplete();
        } else {
          onComplete("invalid user and password combination");
        }
      }, 25); // Delayed processing simulation
    };

    checkAsyncUserPass(pdu.system_id, pdu.password, function (err) {
      if (err) {
        session.send(pdu.response({ command_status: smpp.ESME_RBINDFAIL }));
        session.close();
      } else {
        session.send(pdu.response());
        session.resume();
      }
    });
  });
});

server.listen(2775);
```

SMPP session

```
var smpp = require('smpp');

var session = smpp.connect({
  url: 'smpp://localhost:2775',
  auto_enquire_link_period: 10000,
  debug: true
}, function () {
  session.bind_transceiver({
    system_id: 'YOUR_SYSTEM_ID',
    password: 'YOUR_PASSWORD'
  }, function (pdu) {

    if (pdu.command_status === 0) {
      // Successfully bound
      session.submit_sm({
        destination_addr: '+34xxxxxxxxx',
        short_message: 'Hello'
      }, function (pdu) {
        if (pdu.command_status === 0) {
          // Message successfully sent
          console.log(pdu.message_id);
        }
      });
    }
  });
});


session
```

I can check that the submit_sm event is receiving but I am not receiving the sms on my mobile phone. 

But with this example, which are the values for system_id and password variables? I dont understant the value of this variables.

Have I missed listen some extra event? I am not able to receive any message.

Another question is If the country code for phone number is with plus code '+34' or '34' at the beggining of the destination_addr variable. Btw, I have tried with both.

Thanks!

**Comment by aflorom** [comment]
Hi @juliangut 

Ok, I understand you now. I am confused about it. I did not know how I could sent messages without credit but now You have resolved that dude. I did not know the SMSC was necessary in that. 

But now, I do not know how get the system_id and password from a sim of a mobile phone. How Can I get that values for system_id and password or are there another possibilities for serving a SMSC? 

Thanks!

**Comment by juliangut** [comment]
Glad to hear that

About available SMSC, there are plenty of them, some give a global coverage at a higher cost and some others are more localized and may have better prices, you should look into what your requirements are before selecting one blindly

I'm not going to publicly advocate for any SMSC here, if you need more info on SMS providers send me an email

Regards
