### ISSUE TITLE
Query : regarding a line of code

### ISSUE THREAD

**Issue by polsumeet3666** [farhadi/node-smpp#196]
Hi @juliangut ,
in defs.js inside filters.message
is there any particular reason why you are performing below highlighted statement
![image](https://user-images.githubusercontent.com/35520546/141471840-94251ab8-0d2c-4117-abc3-e6de72ecf482.png)

I have forked the repo to add encoding support for class 0 (flash messages) with character set UCS-2
DCS 0x18 (24) input but after & operation with 0x0F the value is changed to 8
but due to above statement. the short message is encoded incorrect.
although during sending on socket is encoded properly, but in application its creating problem.

Thanks in advanced.

**Comment by juliangut** [comment]
The reason for that line is to ensure data_coding value is between 0x00 and 0x0F which are the values supported by the list of encodings: https://github.com/farhadi/node-smpp/blob/master/lib/defs.js#L1385

**Comment by juliangut** [comment]
Closing as I believe it's already been answered. Feel free to reopen if needed
