### ISSUE TITLE
DCS=4 as SMPP Server

### ISSUE THREAD

**Issue by fardhana** [farhadi/node-smpp#197]
Hi All,

I am successfully build an SMPP using this library.
Now we try to build something new that require SMPP server using DCS=4 (binary message).

Does this library support to provide this requirement?
Thanks!

**Comment by juliangut** [comment]
Hi @fardhana 

Have a look at this issue regarding sending binary content https://github.com/farhadi/node-smpp/issues/74

At this moment there is no implementation to encode/decode binary, it should be added in the same fashion it is done here: https://github.com/farhadi/node-smpp/blob/master/lib/defs.js#L392

You can add it at exec time by
```nodejs
const smpp = require('smpp');
smpp.encodings.BINARY = {
  match: function (value) {
    // implement
  },
  encode: function (value) {
    // implement
  },
  decode: function (value) {
    // implement
  }
};
```

Feel free to PR

**Comment by juliangut** [comment]
Closing as I believe it's already been answered. Feel free to reopen if needed
