### ISSUE TITLE
Close callback called too early

### ISSUE THREAD

**Issue by peter-vasarhelyi** [farhadi/node-smpp#200]
Hello!

When I call the `Session.close` method with a callback, I think it is called too early (immediately). I believe the bug lies here: https://github.com/farhadi/node-smpp/blob/master/lib/smpp.js#L237
When I negate the condition it works properly. The same applies to the `destroy` function

**Comment by ajamous** [comment]
Thanks @peter-vasarhelyi , do you think this can lead to #205 ?

**Comment by juliangut** [comment]
The PR has been merged
