### ISSUE TITLE
MCCMNC info

### ISSUE THREAD

**Issue by guicuton** [farhadi/node-smpp#217]
Hi guys!

first of all, amazing lib!
very friendly and easy to use!

I would like to know if is there a way to get the MCCMNC (carrier) of the mobile that we sent through submit_sm since the providers by default don't give us back this info by deliver_sm.

This would be very usefull to create rules of message routing through each carrier

**Comment by juliangut** [comment]
Hi @guicuton 

The only way to have this information is through your providers in deliver_sm PDUs

Contact your provider and ask them if they can provide MCC/MNC in a custom TLV, and what the configuration for that TLV is

```
smpp.addTLV('mccmnc', { id: 0x1441, type: smpp.types.tlv.string });
```

After gathering that it's as simple as registering your TLV and then extracting it from the PDU itself

```
const mccmnc = pdu.mccmnc;
```

**Comment by guicuton** [comment]
Hi @juliangut 

Thanks for your information!
