### ISSUE TITLE
Send mesage

### ISSUE THREAD

**Issue by batazor** [farhadi/node-smpp#22]
prompt, that would send a message **session.submit_sm** must be within **session.bind_transceiver** or can be placed outside?

for example, it will be clear what I mean https://gist.github.com/batazor/7679c14e08b7ae90f643

**Comment by daper** [comment]
This will help you, from the spec:
"An SMPP session between an SMSC and an ESME is initiated by the ESME first establishing a network connection with the SMSC and then issuing an SMPP Bind request to open an SMPP session. An ESME wishing to submit and receive messages is required to establish two network connections (TCP/IP or X.25) and two SMPP sessions (Transmitter and Receiver). Alternatively, in this version of the protocol an ESME may establish an SMPP Transceiver session over a single network connection."

It means you have to send first successfully bind_{transceiver || receiver && transmitter}, in your case transceiver or transmitter. So if you want to be sure your session is valid, include submit_sm inside your bind_transceiver callback and check out the command_status in bind_transceiver_resp as it shows in docs.

**Comment by batazor** [comment]
Thank you for your response.

**Comment by navsaini53** [comment]
submit_sm_resp give pdu that contain "message_id" and command_status=0  now from here i want MC to send delivery status back to SMSE how would i do this ?  I means implementation of delivery_sm operation in transceiver ??

help

**Comment by farhadi** [comment]
@navsaini53 You need to register a deliver_sm pdu handler:
```
session.on('deliver_sm', function(pdu) {
    console.log(pdu.short_message);
    session.send(pdu.response());
});
```
`short_message` content in `deliver_sm` is something like this:
`id:23787281946 sub:001 dlvrd:001 submit date:1510032311 done date:1510032311 stat:DELIVRD err:null text:DELIVRD`

Also don't forget to set `registered_delivery` to `1` when sending `sumbit_sm`.

See this link for more details: http://www.smssolutions.net/tutorials/smpp/smppdeliveryreports/
