### ISSUE TITLE
Content issue - 1b2f ( \ ) --> 00 ( @ ) 

### ISSUE THREAD

**Issue by ajamous** [farhadi/node-smpp#222]
There is an issue that seems to be coming from the node SMPP library

Sample:

Original content by message originator:
```log 
hgHxcXCKGL 811279 /!@#$%^&*()+{}|:"<>?/-=[]\;',.¥£€/ABCDEFGHIJKLMNOPQRSTUVWXYZ~/(0000)
```

Content delivered to the upstream carrier:

```log
hgHxcXCKGL 811279 /!@#$%^&*()+{}|:"<>?/-=[]@;',.¥£€/ABCDEFGHIJKLMNOPQRSTUVWXYZ~/(0000)
```
Changed/Minuplated character:

1b2f ( \ ) change to  00 ( @ )

![](https://user-images.githubusercontent.com/26701933/204593051-a902ad39-1512-4b6d-a1fc-e885cf330985.png)

the image above shows the bytes of the message.. to the left is the one for the message sent from node-smpp to the upstream

The message originator is using `DCS 0`.. and indeed the first message has the `1b2f (\)` but when it comes back has 00 (@) instead.

We also have tested the latest SMPP library version, which seems to still change` \ ` to  `\\` instead of  `\  -> @`  

cc: @juliangut

**Comment by ajamous** [comment]
The issue is actually already resolved in the latest library version https://github.com/farhadi/node-smpp/commit/85b6a23037de9b07453e4f83c14991f1aa7c8d19 . regarding the backslash becoming a double backslash it is not the library issue, it is just the way console.log works in javascript.

**Comment by juliangut** [comment]
Thank you for giving an answer and closing the issue
