### ISSUE TITLE
Cannot set bytes in UDH header larger than 127 

### ISSUE THREAD

**Issue by jaroszan** [farhadi/node-smpp#23]
I am bulding message_payload by concatenating bytes in the following way:

    // UDH header
    var session_id = new Buffer(4);
    session_id.writeUInt8(5, 0);
    session_id.writeUInt8(0, 1);
    session_id.writeUInt8(3, 2);
    session_id.writeUInt8(227, 3);

    var message_part1 = new Buffer([2, 1]);
    var message_part2 = new Buffer([2, 2]);

    // message parts
    var message1 = Array(153).join("A")
    var message2 = Array(153).join("B")

    var part1 = new Buffer(message1);
    var part2 = new Buffer(message2);

    // Setting message payload field inside the deliver_sm function
    message_payload: session_id + message_part2 + part2

Setting byte to be larger than 127 causes trouble and the whole message gets messed up by encoding message body to UCS2 encoding

According to specs (3GPP TS 23.040) sequence number of a message can have range from 0 to 255, however I am not able to set it in node-smpp.

Am I misusing the library or is it a bug?

===================

EDIT: I have tried to concatenate buffer (Buffer.concat) before assigning to message_payload and verifying it with Buffer.isBuffer function and the value I am providing to message_payload is a buffer. It looks that message_payload has a filter which checks whether field value is a buffer and should use unmodified value if true. But it seems it converts it anyway.

    var bufferArr = [session_id, message_part2, part2];
    var concatenatedBuf = Buffer.concat(bufferArr);

    message_payload: concatenatedBuf

====================

EDIT: I have removed filters.message for message_payload in defs.js and it worked, so the problem is somewhere in filters.message function.

**Comment by farhadi** [comment]
You can specify udh part separately in your message:
```
var pdu = new smpp.PDU('deliver_sm', {
	message_payload: {
		udh: new Buffer([5, 0, 3, 227, 2, 2]),
		message: Array(153).join("B")
	}
});
```
Also, as you said, passing a buffer will bypass message filter.
The following code approves it:
```
var smpp = require('smpp');
var assert = require('assert');
// UDH header
var session_id = new Buffer([5, 0, 3, 227]);

var message_part1 = new Buffer([2, 1]);
var message_part2 = new Buffer([2, 2]);

// message parts
var message1 = Array(153).join("A")
var message2 = Array(153).join("B")

var part1 = new Buffer(message1);
var part2 = new Buffer(message2);

// Setting message payload field inside the deliver_sm function
var bufferArr = [session_id, message_part2, part2];
var concatenatedBuf = Buffer.concat(bufferArr);

var pdu = new smpp.PDU('deliver_sm', {
	message_payload: concatenatedBuf
});

var b = pdu.toBuffer();

smpp.tlvs.message_payload.filter = null;
var pdu = new smpp.PDU('deliver_sm', {
	message_payload: concatenatedBuf
});

var b2 = pdu.toBuffer();

assert.deepEqual(b,b2);
```
