### ISSUE TITLE
Differntiate between incoming message and an incoming message that gets triggered after a message is sent using smpp

### ISSUE THREAD

**Issue by aTrueSeeker** [farhadi/node-smpp#238]
I noticed that after connecting a transceiver the deliver_sm gets fired after my app sends a message and it looks like
![image](https://github.com/farhadi/node-smpp/assets/45688400/a7ad149c-3d6b-44fe-b6be-323d4981668c). How can i differentiate between this message and other incoming messages that is being sent

**Comment by guicuton** [comment]
This message that you received on `deliver_sm`is the DELIVERY REPORT of sent message (DLR)
For incoming messages (MO / 2way message) the `esm_class` param will be different of 4.

Just do a simple `if()` condition with this and you will be good to go like:

```js
session.on('deliver_sm', (pdu) => {
    if(pdu.esm_class === 4) {
        console.log(pdu, 'DLR');
     }
     
     if(pdu.esm_class !== 4) {
         console.log(pdu, 'MO');
    }
})
```

**Comment by aTrueSeeker** [comment]
Thanks  @guicuton  for the prompt response. :bow:
