### ISSUE TITLE
connection issue when setting up the smpp server.

### ISSUE THREAD

**Issue by theiceeman** [farhadi/node-smpp#240]
The package requires a system-id and a password for the server to run successfully.
How do i get these details please.
Thanks.

**Comment by guicuton** [comment]
If you are as client these details you will get from your smsc provider

As server you will provide this for yours users

**Comment by theiceeman** [comment]
Hi Guilherme, Thanks for the reply.
can you suggest preferred sms centers that offer this service globally?

Is Twilio a valid option?

I basically need to be able to receive sms on my server.

**Comment by guicuton** [comment]
> Hi Guilherme, Thanks for the reply. can you suggest preferred sms centers that offer this service globally?
> 
> Is Twilio a valid option?
> 
> I basically need to be able to receive sms on my server.

Yes. There is a lot of providers.
Just google "SMPP provider" then you'll find a lot of good options.

**Comment by theiceeman** [comment]
Alright
Thanks

**Comment by elhananjair** [comment]
@theiceeman this issue can be closed.

**Comment by theiceeman** [comment]
yes, sure
Thanks
