### ISSUE TITLE
Sending binary messages

### ISSUE THREAD

**Issue by ghost** [farhadi/node-smpp#25]
To send binary messages is sufficient to establish the value data_coding - 4? I get an error:

[TypeError: Can not read property 'length' of indefinedsch

subtit_sm:
session.submit_sm({
    destination_addr    : message.phone,
    message_payload     : message.data,
    registered_delivery : 1,
    data_coding         : 4
  }, function(pdu) {
    if (pdu.command_status == 0) {
      ...
    } else {
      ...
    }
});

https://gist.github.com/xorumtes/19f1c3aeb2a7708037ca

**Comment by hkulekci** [comment]
you must give more information about message.data. did you encode your data and split it?

**Comment by farhadi** [comment]
To send binary messages `message_payload` must be of type `Buffer`. make sure your `message.data` is a `Buffer`.
