### ISSUE TITLE
How to pass extra data to submit_sm options

### ISSUE THREAD

**Issue by Sukhrob** [farhadi/node-smpp#27]
I want to insert an SMS to the database after submitting. How to pass extra data (custom data like client_id which is specific to my app) to submit_sm options.

**Comment by ti24horas** [comment]
@Sukhrob you're doing the inverse.
Normally, you wait for the response for submit_sm (submit_sm_resp) and associate the message_id with your database.

**Comment by Sukhrob** [comment]
Thanks for your response @ti24horas. Here is the code:

    var sms = JSON.parse(data); // Coming from RabbitMQ consumer

    // Send an SMS
    session.submit_sm({
        registered_delivery: true,
        source_addr: sms.sender,
        destination_addr: sms.recipient,
        short_message: sms.message
    }, function (pdu) { // Here, I would want to bind each client to their own SMSs like this if possible: function (pdu, sms) {
        var parameters = {
            client_id: sms.client_id, // Is it safe to put client_id here directly as it is an asynchronous request?
            sender: pdu.source_addr,
            recipient: pdu.destination_addr,
            message: pdu.short_message,
            message_id: pdu.message_id,
            status: pdu.command_status,
            created_at: new Date()
        };

        // Save an SMS to the database
    });

Say, if there are 10 clients which send a lot of SMSs per second, can one client overwrite another one's SMS?

**Comment by farhadi** [comment]
If your code is inside a function scope and you call submit_sm once in this scope (i.e. not in a loop) and you don't alter `sms` variable in this scope later, it's most likely safe to use the code you quoted.
