### ISSUE TITLE
Sender ID configurable?

### ISSUE THREAD

**Issue by lifehome** [farhadi/node-smpp#29]
Just curious if I could set the sender ID?

**Comment by alefalezza** [comment]
Yes, you can set the pdu "source_addr" field like this:

     session.submit_sm(
        {
            source_addr: senderId
        }, 
        function(pdu) {
        ...
        });

**Comment by farhadi** [comment]
As alefalezza said, you can use source_addr parameter.
If you have any questions, don’t hesitate to let us know!
