### ISSUE TITLE
Mismatch between data_coding and short_message.message after decode

### ISSUE THREAD

**Issue by alefalezza** [farhadi/node-smpp#30]
Receiving an message submit_sm of this type:

    new smpp.PDU('submit_sm', {
         'data_coding': 8,
         'short_message': new Buffer("0043006f0043006f0043006f0043006f0043006f", "hex")
     });

the server decodes it with filters.message.decode (in defs.js) and decodes the message from UCS2 without changing data_coding field.
So we have 'data_coding': 8 and short_message coded as Buffer("436f436f436f436f436f", "hex"), that is not UCS2 coding, is it ok?
If we have to store the decoded PDU without re-encoding, the data_coding is wrong...

**Comment by alefalezza** [comment]
We can suggest you two mods.

The first one is to alter "_filter('encode')" with something like this:

    if (message && (this.data_coding === null || this.data_coding != consts.ENCODING[encoding]))

The second one is to modify "_filter('decode')" this way:

    if (encodings[encoding]) {
        result.message = encodings[encoding].decode(result.message);
        if (this.data_coding != consts.ENCODING[encodings.detect(result.message)]) {
            this.data_coding = consts.ENCODING[encodings.detect(result.message)];
        }
    }

**Comment by farhadi** [comment]
Message filter is meant to decode the message to a regular javascript string.
If you need the original message, you can remove message filter:
`smpp.commands.submit_sm.params.short_message.filter = false;`

Or just disable the decoder but not the encoder:
`smpp.filters.message.decode = function(value) { return value };`
