### ISSUE TITLE
TLV Data

### ISSUE THREAD

**Issue by yepher** [farhadi/node-smpp#31]
I have your sample code which works fine with one SMPP server but in another case I am have having a problem. This is what I have:

```
var smpp = require('smpp');
var session = smpp.connect('smpp_server', 2775);
session.bind_transceiver({
    system_id: 'smppclient1',
    password: 'password'
}, function(pdu) {
    if (pdu.command_status == 0) {
        // Successfully bound
        session.submit_sm({
            destination_addr: '8475551212',
            short_message: 'Hello!'
        }, function(pdu) {
            if (pdu.command_status == 0) {
                // Message successfully sent
                console.log(pdu.message_id);
            }
        });
    }
});

```

Turns out I need to send TLV like this one:

```
abc42xyz_operator,   0x1520,1,5, 5,0x03,CUSTMR_13914533_TESTIPC_111_D
```

I looked at the GitHub page and I see you mention TLV as an Array but I don't see how it would be put into the javascript.

I see this in smpp.js but I am not sure how to apply that to the TLV:

```
exports.addTLV = function(tag, options) {
	options.tag = tag;
	defs.tlvs[tag] = options;
	defs.tlvsById[options.id] = options;
};
```

**Comment by ihusejnovic** [comment]
Try:
```javascript
smpp.tlvs['abc42xyz_operator'] = {
	id: 0x1520,
	type: smpp.types.tlv.string
};

session.submit_sm({
                destination_addr: '8475551212',
                short_message: 'Hello!',
                abc42xyz_operator: 'CUSTMR_13914533_TESTIPC_111_D'    
           }, function(pdu) {
                if (pdu.command_status == 0) {
                    // Message successfully sent
                    console.log(pdu.message_id);
                }
           });

```

**Comment by yepher** [comment]
Yes, you were exactly right. Thank you. I've seen question here and there for how to do this. I will add an example to the README and send a pull request. Use it if you want.

**Comment by farhadi** [comment]
The correct way to add a custom TLV is by using addTLV method like this:

smpp.addTLV('abc42xyz_operator', {
    id: 0x1520,
    type: smpp.types.tlv.string
});

**Comment by yepher** [comment]
Do you still need this in the sumit_sm body?

**Comment by farhadi** [comment]
Yes, you need to use addTLV once to tell smpp module how to handle a `abc42xyz_operator` TLV parameter. And then you can use this TLV parameter in your PDUs e.g. in a submit_sm.

**Comment by yepher** [comment]
Since you said to only include once is this what you mean?

**Comment by farhadi** [comment]
Yes, that is exactly how addTLV method should be used.

**Comment by yepher** [comment]
Thanks @farhadi 

By the way this is a very nice tool you have built.

**Comment by farhadi** [comment]
@yepher Thanks for your interest.
