### ISSUE TITLE
Binary Message

### ISSUE THREAD

**Issue by yepher** [farhadi/node-smpp#33]
How to send a specific UDH?

As a practical example, say I want to create a UDH to send a WAP Push, where the standard destination port for WAP pushes is 2948, the UDH will be:

```
06 05 04 0B 84 23 F0 
```
**where:**

* 06 means “read the following 6 bytes”
* 05 is the format for numbers, in this case hexadecimal numbers
* 04 will tell the UDH that each port is represented using 4 character
* 0B84 is the destination port, 2948 (decimal representation) or 0B84 (hexadecimal representation)
* 23F0 is the source port, 9200 (decimal representation) or 23F0 (hexadecimal representation).

I've tried playing around with this example but can't quite figure out how to get what I need:
* https://github.com/farhadi/node-smpp/blob/master/test/pdu.js#L8

I will be sending a string in the payload.

This is an example of message:

xample message: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXY00
Binary SMS with user data unencoded. Src port 8880 and Dest port is 8888. 

PID - 0x00
DCS- 0x00
UDH- 0x0605040B8423F0 
UD - 0x6162636465666768696A6B6C6D6E6F707172737475767778797A4142434445464748494A4B4C4D4E4F505152535455565758593030

**Comment by yepher** [comment]
I just found this issue which I think answers my question:

https://github.com/farhadi/node-smpp/issues/23

Checking to make sure it works.

**Comment by farhadi** [comment]
You can pass udh and message separately:
```
session.submit_sm({
  short_message: {
    udh: new Buffer('0605040B8423F0', 'hex')
    message: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXY00'
  }
});
```

**Comment by yepher** [comment]
I assume the code will automatically handle settings

These fields as needed?

data_coding: 245,
esm_class: 64,

**Comment by farhadi** [comment]
When you provide a udh in your short_message parameter, esm_class will be automatically set to 0x40 (UDH_INDICATOR). 
data_coding will also be automatically set to 0x01, 0x03, and 0x08 depending on the detected encoding of the message.

Other values for esm_class and data_coding should be handled manually.

**Comment by samayool** [comment]
I want to send Binary message but I receive 
"command_status: 1078"  

the code I am using is : 
session.submit_sm({
            short_message: {
                source_addr: 'XXXXXXXXXXX',
                destination_addr:'YYYYYYYYYYY',                
                udh: new Buffer('0605040B8423F0', 'hex'),              
                message: '02056A0045C60C037777772E6465762E6D6F62692F69735F66756E2E68746D6C0011033635333200070103446576446F744D6F62692069732046756E2021000101',
                
            }
        }, function(pdu) {
            console.log('binary callback')
            console.log(pdu);
           
            }
        });

can you address me to the problem ?

**Comment by ritmas** [comment]
AFAIK error codes bigger than `255 (0x000000FF)` is customly-defined by SMSC, so it's not SMPP standard. Can you share the full PDU?

**Comment by samayool** [comment]
thank you for your reply 
this is the PDU:

PDU {
  command_length: 16,
  command_id: 2147483652,
  command_status: 1078,
  sequence_number: 6072,
  command: 'submit_sm_resp' }

**Comment by ritmas** [comment]
No, I don't see anything interesting.. If you have access to SMSC, try analyzing the logs there, catch network packets with wireshark & analyze them, maybe it would help you.
