### ISSUE TITLE
Why message states are incomplete

### ISSUE THREAD

**Issue by Sukhrob** [farhadi/node-smpp#34]
According to the SMPP 3.4 docs, there are 10 message states:

0	SCHEDULED	The message is scheduled for later sending.
1	ENROUTE	The message is enroute.
2	DELIVERED	The message was successfully delivered.
3	EXPIRED	The SMSC was unable to deliver the message in a specified amount of time.For instance when the phone was turned off.
4	DELETED	The message was deleted.
5	UNDELIVERABLE	The SMS was unable to deliver the message.For instance, when the number does not exist.
6	ACCEPTED	The SMS was accepted and will be send.
7	UNKNOWN	Unknown error occured.
8	REJECTED	The message was rejected.The provider could have blocked phonenumbers in this range.
9	SKIPPED	The message was skipped.

But, only 6 of them are provided in defs.js file.

**Comment by tsypa** [comment]
from defs.js
MESSAGE_STATE: {
		SCHEDULED:     0,
		ENROUTE:       1,
		DELIVERED:     2,
		EXPIRED:       3,
		DELETED:       4,
		UNDELIVERABLE: 5,
		ACCEPTED:      6,
		UNKNOWN:       7,
		REJECTED:      8,
		SKIPPED:       9
	},

**Comment by Sukhrob** [comment]
I had to "npm update" to see this. But, I am sure the rest of them were added within 4 months. Thanks @tsypa
