### ISSUE TITLE
query_sm

### ISSUE THREAD

**Issue by eltinsalerno** [farhadi/node-smpp#35]
Hi!!

When I use query_sm always return generic_nack.

pdu { command: 'query_sm',
  command_length: 41,
  command_id: 3,
  command_status: 0,
  sequence_number: 2,
  message_id: '9066579236',
  source_addr_ton: 1,
  source_addr_npi: 1,
  source_addr: '506848xxxxx' }

pdu { command_length: 16,
  command_id: 2147483648,
  command_status: 3,
  sequence_number: 2,
  command: 'generic_nack' }

**Comment by tsypa** [comment]
check this with network sniffer,
perhaps your SMSC send generic_nack in response to query_sm

**Comment by farhadi** [comment]
It's most probably because your SMSC doesn't support query_sm.
