### ISSUE TITLE
Session close event is emitted after a successful bind_transceiver method

### ISSUE THREAD

**Issue by Sukhrob** [farhadi/node-smpp#36]
session.bind_transceiver({
        system_id: 'system_id',
        password: 'password'
    }, function (pdu) {
        if (pdu.command_status != smpp.errors.ESME_ROK) {
            console.error('SMPP bind transceiver error: ' + pdu.command_status);
            process.exit(1);
        } else {
            console.log('Connected');
        }
    });

    session.on('close', function () {
        console.log('SMPP connection is closed');
    });

Output: Connected, SMPP connection is closed

Why is the session close event emitted after a successful bind_transceiver method?

**Comment by tsypa** [comment]
Perhaps it is because the SMSC sends the appropriate packet
I think You should check this with sniffer and|or  PDUs debug output.

**Comment by Sukhrob** [comment]
This is a pdu after a successful bind_transceiver method

{ command_length: 22,
  command_id: 2147483657,
  command_status: 0,
  sequence_number: 1,
  command: 'bind_transceiver_resp',
  system_id: '',
  sc_interface_version: 80 }

**Comment by Sukhrob** [comment]
Even enquire_link is not working. It worked before I updated the module with npm.

    session.on('enquire_link', function (pdu) {
        session.send(pdu.response());
    });

**Comment by tsypa** [comment]
Can you sniff session?

**Comment by Sukhrob** [comment]
After binding a transceiver successfully?

**Comment by tsypa** [comment]
If SMSC is buggy :)

**Comment by Sukhrob** [comment]
How to send a enquire_link to check this? There is no example in the docs.

**Comment by tsypa** [comment]
I got same result w/ closed session
going to investigate

**Comment by tsypa** [comment]
What SMSC provider you use?
If session is closed without preliminary PDU that most likely ESME receives FIN ACK.
I found a bug in my own SMSC  which increases enquire_link timeout on the disconnected ESMEs and 
closes clonnection after binding by session.close()
If your SMSC has similar bug and you don't have access to source code to fix it then 
second bind attempt after session 'close' event can help.

**Comment by Sukhrob** [comment]
The SMSC provider which I am using allows only one connection at a time. In order to send a lot of SMSs, I was trying to establish a connection from each of my web servers. After turning off one of servers, the connection from the other server to SMSC started working. Plus, I configured to send enquire links from my server in addition to responding to enquire links from SMSC. Now, I can keep the connection even days. That's cool. @tsypa Thanks for your help.

**Comment by tsypa** [comment]
In this case, the proxy can be also a solution
Happy to help :)

**Comment by MukitCSTE** [comment]
Error: PDU length was too large (1195725856, maximum is 16384).
    at Function.PDU.fromStream (C:\Users\HP\node_modules\smpp\lib\pdu.js:49:9)
    at Session._extractPDUs (C:\Users\HP\node_modules\smpp\lib\smpp.js:59:20)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)

**Comment by MukitCSTE** [comment]
I can't create SMPP server .

Error: PDU length was too large (1195725856, maximum is 16384).
    at Function.PDU.fromStream (C:\Users\HP\node_modules\smpp\lib\pdu.js:49:9)
    at Session._extractPDUs (C:\Users\HP\node_modules\smpp\lib\smpp.js:59:20)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
