### ISSUE TITLE
How to send a long SMS message to CDMA providers which do not support message_payload

### ISSUE THREAD

**Issue by Sukhrob** [farhadi/node-smpp#37]
There are no examples of sending a long SMS message when message_payload is not supported. @vchatterji suggests using "gsm" package in the issue "https://github.com/farhadi/node-smpp/issues/4". But, I am not sure whether it works with CDMA providers.
Any suggestions or code examples?

**Comment by halex2005** [comment]
You can chop your long SMS to chunks with [User Data Header](https://en.wikipedia.org/wiki/User_Data_Header) structure in short_message pdu field.
Try it, I have no code example though.

**Comment by halex2005** [comment]
I found example in neighbor issue: [try it out](https://github.com/farhadi/node-smpp/issues/33#issuecomment-166210288)

**Comment by farhadi** [comment]
I think vchatterji's example using `gsm` package would work for you.
