### ISSUE TITLE
Delivery Report 

### ISSUE THREAD

**Issue by mamoste** [farhadi/node-smpp#42]
How do I get SMS status report? 
 using node js and express

**Comment by luishdez** [comment]
+1 Yep some docs about receiving delivery reports will be nice.

**Comment by mamoste** [comment]
thank you, great!

**Comment by mamoste** [comment]
So what do I need to send SMS to multiple numbers?

**Comment by luishdez** [comment]
You have to `submit_sm` for each SM

```
    session.submit_sm({
      registered_delivery: 1,
      destination_addr: '+34676300300',
      source_addr: 'SENDERXX',
      short_message: 'Hello Buddy'
    }, function(pdu) {
      if (pdu.command_status == 0) {
        console.log('id: %s', pdu.message_id);
      }
```

**Comment by farhadi** [comment]
Thanks @luishdez for the sample code!

**Comment by Ciao121** [comment]
@luishdez what does 
if (pdu.esm_class == 4)
means?

**Comment by luishdez** [comment]
It's defined in the protocol manual https://smpp.org/SMPP_v5.pdf
