### ISSUE TITLE
Pls Help for multi Send sms

### ISSUE THREAD

**Issue by mamoste** [farhadi/node-smpp#43]
hi, how can I send SMS to more than one number? Do you have sample code?

**Comment by farhadi** [comment]
Use "submit_multi" Operation:

session.submit_multi({
    dest_address: [
        {destination_addr: 'DESTINATION NUMBER 1'},
        {destination_addr: 'DESTINATION NUMBER 2'},
        // ...
    ],
    short_message: 'Hello!'
});

**Comment by mamoste** [comment]
PDU {
  command_length: 32,
  command_id: 2147483681,
  command_status: 13,
  sequence_number: 2,
  command: 'submit_multi_resp',
  message_id:** 'Unknown command.' }**

**Comment by mamoste** [comment]
I would be glad if a large sample of code or a large document, Greetings

**Comment by farhadi** [comment]
Before sending submit_multi, make sure your session is already bound.
If your provider doesn't support submit_multi operation use submit_sm in a loop.
