### ISSUE TITLE
session.submit_multi

### ISSUE THREAD

**Issue by mamoste** [farhadi/node-smpp#44]
session.submit_multi({
    dest_address: [
        {destination_addr: 'DESTINATION NUMBER 1'},
        {destination_addr: 'DESTINATION NUMBER 2'},
        // ...
    ],
    short_message: 'Hello!'
});

I did,

PDU {
 command_length: 32,
 command_id: 2147483681,
 command_status: 13,
 sequence_number: 2,
 command: 'submit_multi_resp',
 message_id:** 'Unknown command.' }** --> I get the error

I would be glad if a large sample of code or a large document, Greetings

**Comment by farhadi** [comment]
Before sending submit_multi, make sure your session is already bound.
If your provider doesn't support submit_multi operation use submit_sm in a loop.
