### ISSUE TITLE
Cluster mode?

### ISSUE THREAD

**Issue by alexcrack** [farhadi/node-smpp#46]
I need to run several instances of the application.
How can i use node-smpp in the cluster mode (manually or for example through pm2)? Or maybe use any loadbalancer (haproxy)?

**Comment by daper** [comment]
Checkout this framework http://www.actionherojs.com you can make a
framework server instance that wraps or connects with your smpp code. It's
cluster-ready. I'm working on this approach now.

**Comment by markitosgv** [comment]
There's any problem with session when running with pm2 in cluster mode?

**Comment by 4e1ovek** [comment]
The library is good. A very necessary work in cluster mode.

**Comment by joaodrp** [comment]
@daper have you managed to get it working with actionhero?

**Comment by dareenzo** [comment]
I don't know if this applies as an answer, but I find myself in a situation where I need to support 3 different providers at the same time and I don't want to repeat the code, so what we did is since we've been using PM2 to manage the process we just add 2 more process instances with different configurations for each provider respectively.

PM2 process file uses the usual structure like this:

```json
{
    "apps": [
        {
            "name": "smpp-provider-1",
            "script": "/srv/www/secret-product-name/smpp/app.js",
            "merge_logs": true,
            "error_file": "/srv/www/secret-product-name/log/smpp_provider-1_error.log",
            "out_file": "/srv/www/secret-product-name/log/smpp_provider-1_output.log",
            "watch": true,
            "env": {
                "NODE_ENV": "local",
                "TEST": true,
                "PROVIDER": "provider-1"
            },
            "env_production": {
                "NODE_ENV": "production",
                "PROVIDER": "provider-1"
            },
            "env_staging": {
                "NODE_ENV": "staging",
                "TEST": true,
                "PROVIDER": "provider-1"
            }
        },
        {
            "name": "smpp-provider-2",
            "script": "/srv/www/secret-product-name/smpp/app.js",
            "merge_logs": true,
            "error_file": "/srv/www/secret-product-name/log/smpp_provider-2_error.log",
            "out_file": "/srv/www/secret-product-name/log/smpp_provider-2_output.log",
            "watch": true,
            "env": {
                "NODE_ENV": "local",
                "TEST": true,
                "PROVIDER": "provider-2"
            },
            "env_production": {
                "NODE_ENV": "production",
                "PROVIDER": "provider-2"
            },
            "env_staging": {
                "NODE_ENV": "staging",
                "TEST": true,
                "PROVIDER": "provider-2"
            }
        },
        {
            "name": "smpp-provider-3",
            "script": "/srv/www/secret-product-name/smpp/app.js",
            "merge_logs": true,
            "error_file": "/srv/www/secret-product-name/log/smpp_provider-3_error.log",
            "out_file": "/srv/www/secret-product-name/log/smpp_provider-3_output.log",
            "watch": true,
            "env": {
                "NODE_ENV": "local",
                "TEST": true,
                "PROVIDER": "provider-3"
            },
            "env_production": {
                "NODE_ENV": "production",
                "PROVIDER": "provider-3"
            },
            "env_staging": {
                "NODE_ENV": "staging",
                "TEST": true,
                "PROVIDER": "provider-3"
            }
        }
    ]
}
```

This way we can start and stop each of the processes independently of the others. And within the app code we can fetch the env variable specifying the provider name and know which config file with usernames, passwords, endpoints and etc to pickup.

Hope it helps

**Comment by daper** [comment]
@joaodrp sorry, I started the proyect becouse kannel did not support some tlvs, but now it does. So I never ended, and its in a ver early stage. But Who knows, someday i'll finish it :) then publish it in my github account.

**Comment by juliangut** [comment]
Cluster mode is currently supported for plain connections to the server. There has been a merged PR to fix cluster mode for TLS servers. This will be available in next release

Closing this issue, feel free to reopen if needed
