### ISSUE TITLE
Can i make a simulator using this api

### ISSUE THREAD

**Issue by KumarDedhia** [farhadi/node-smpp#47]
I am trying to recieve deliver_sm and send deliver_sm_resp,
Is their any example which work for me.
Thanks

**Comment by tsypa** [comment]
session.on('deliver_sm', function(pdu) {
  session.deliver_sm_resp({sequence_number:pdu.sequence_number});
});

**Comment by dareenzo** [comment]
@tsypa answer may be right.

But I would also like to suggest using [SMPPSim](http://www.seleniumsoftware.com/downloads.html), a SMPP server simulator which has a graphical interface that allows you to see both incoming and outgoing messages as well as inputting them, changing and tweaking settings.

Bellow is it's short description
> SMPPSim is a SMPP SMSC simulation tool, designed to help you test your SMPP based application. SMPPSim is free of charge and open source.

Hope it helps.
