### ISSUE TITLE
Add auto close with enquire link support for server

### ISSUE THREAD

**Issue by luishdez** [farhadi/node-smpp#49]
enquire link event is used to keep the server alive. In most servers this is defined with a timer. Eg: 60s where users must send a enquire_link to avoid the close of the session.

This could be integrated in this module with a config option. Since this feature will be the same for all the user.

**Comment by farhadi** [comment]
Thanks for the suggestion. I will add it in a future version.

**Comment by juliangut** [comment]
merged
