### ISSUE TITLE
Need to send Bulk SMS

### ISSUE THREAD

**Issue by Sankaravelu** [farhadi/node-smpp#51]
Is it possible to send Bulk SMSs  using  submit_multi method? I tried using your API but no luck :( . If possible to could you please share a code snippet to send Bulk SMS?

**Comment by Arthur-W-White** [comment]
Were you able to find a solution?

**Comment by daper** [comment]
Take a look at issue #44 and @farhadi answer.

**Comment by juliangut** [comment]
Hi @Sankaravelu I'm cleaning the repository and your question is nearly 3 years old

If you feel this needs a better answer please open a new issue, in the mean time as farhadi comments use submit_sm in a loop if your provider doesn't support it, which in turn seems to be the best solution for compatibility
