### ISSUE TITLE
Cannot send SMS with over 255 chars.

### ISSUE THREAD

**Issue by habaongoc** [farhadi/node-smpp#56]
Hi, 
I got an issue sending SMS when I send an SMS with 280 chars. Is it possible to send message over 255 chars, If yes, Please help me how to fix it or show me what did I do wrong. Thank sa lot.

Here is my code to submit_sm:
`session.submit_sm({`
`    source_addr: 'TEST',`
`    destination_addr: number,`
`   	short_message: message`
`}, function(pdu) {`
`    if (pdu.command_status == 0) {`
`        console.log("- submit_sm success",pdu.message_id);`
`            session.close();`
`   }`
`    else{`
`        console.log("- submit_sm fail:", pdu);`
`        session.close();`
`    }`
`});`

Here is error log: 
`0|DMV-VNP: | TypeError: "value" argument is out of bounds`
`0|DMV-VNP: |     at checkInt (buffer.js:1026:11)`
`0|DMV-VNP: |     at Buffer.writeUInt8 (buffer.js:1074:5)`
`0|DMV-VNP: |     at Object.write (/home/dmvit/testSMS/SMS/node_modules/smpp/lib/defs.js:86:11)`
`0|DMV-VNP: |     at PDU.toBuffer (/home/dmvit/testSMS/SMS/node_modules/smpp/lib/pdu.js:175:20)`
`0|DMV-VNP: |     at Session.send (/home/dmvit/testSMS/SMS/node_modules/smpp/lib/smpp.js:97:24)`
`0|DMV-VNP: |     at Array.<anonymous> (/home/dmvit/testSMS/SMS/routes/index.js:42:18)`
`0|DMV-VNP: |     at Session._extractPDUs (/home/dmvit/testSMS/SMS/node_modules/smpp/lib/smpp.js:69:40)`
`0|DMV-VNP: |     at emitNone (events.js:86:13)`
`0|DMV-VNP: |     at Socket.emit (events.js:185:7)`
`0|DMV-VNP: |     at emitReadable_ (_stream_readable.js:432:10)`
`0|DMV-VNP: |     at emitReadable (_stream_readable.js:426:7)`
`0|DMV-VNP: |     at readableAddChunk (_stream_readable.js:187:13)`
`0|DMV-VNP: |     at Socket.Readable.push (_stream_readable.js:134:10)`
`0|DMV-VNP: |     at TCP.onread (net.js:548:20)`

**Comment by Sukhrob** [comment]
@habaongoc Are you testing with GSM or CDMA operator? If it is GSM, then use "message_payload" instead of "short_message". If it is CDMA, you must send multiple messages. Please, refer to this link https://github.com/farhadi/node-smpp/issues/4

**Comment by notgiorgi** [comment]
I'm using `message_payload`, also setting `sm_length` to 0.
Messages are delivered but they're empty, what could be a problem? I'm testing with GSM operator.

**Comment by Sukhrob** [comment]
@notgiorgi Please, try without setting sm_length to 0. If it doesn't work, can you provide an example source code or at least the one that looks like yours?

**Comment by notgiorgi** [comment]
@Sukhrob I tried, It didn't work. I think it's provider's problem.

I solved problem using this answer: https://github.com/farhadi/node-smpp/issues/4#issuecomment-150810079

```javascript
    calculateMessageUHD(sms) {
        const info = gsm(sms)
        const cref = this.concat_ref
        return info.parts.map((part, i) => {
            
            let udh = new Buffer(6)
            udh.write(String.fromCharCode(0x5), 0) //Length of UDF
            udh.write(String.fromCharCode(0x0), 1) //Indicator for concatenated message
            udh.write(String.fromCharCode(0x3), 2) //  Subheader Length ( 3 bytes)
            udh.write(String.fromCharCode(cref), 3) //Same reference for all concatenated messages
            udh.write(String.fromCharCode(info.sms_count), 4) //Number of total messages in the concatenation
            udh.write(String.fromCharCode(i + 1), 5) //Sequence number ( used by the mobile to concatenate the split messages)

            return {
                udh: udh,
                message: part,
            }
        })
    }
```

then while sending `submit_sm`:
```javascript
short_message: {
        udh: part.udh,
        message: part.message,
},
```

**Comment by habaongoc** [comment]
Many thanks to @Sukhrob and @notgiorgi . I sent it successfully by changing short_message to message_payload. 
Sorry for my late reply because I didn't work for this project shortly.

**Comment by Sukhrob** [comment]
@habaongoc Can you put this code:

    router.get('/sendSMS', function(req, res, next) {
        var number = req.query.number;
	var message = req.query.message;
	console.log("number",number,"message",message)

    session.submit_sm({
        source_addr: 'ABC',
        destination_addr: number,
        message_payload : message,
		source_addr_ton: 5,
		source_addr_npi: 1,
		dest_addr_ton: 1,
		dest_addr_npi: 1,
    }, function(pdu) {
        //console.log("- submit_sm pdu:", pdu)
        if (pdu.command_status == 0) {
            console.log("- submit_sm success",pdu.message_id);
              res.send({errorCode:pdu.command_status, errorMessage: 'Send message success'});
       }
        else{
            console.log("- submit_sm fail:", pdu);
              res.send({errorCode:pdu.command_status, errorMessage: 'Send message fail'});
        }
    });
});

after this code and check it again

    // Successfully bound
    console.log("Successful bound!");

I think you are trying to send an SMS before connecting.

**Comment by habaongoc** [comment]
Hi @Sukhrob,
It's same as my code (I tried your suggestion) because after log : "Successful bound!" show on the console, I call api "/sendSMS". Both is not work.
My solution now is: send a SMS notify to my number (is it cheating?) after "Successful bound!" - (of course I wont receive it). But I don't think it s good idea 
It's like, I need to session.send(..) once, and then everything will smooth later.

**Comment by alepoabhishek** [comment]
just a suggestion:

`var session = smpp.connect('smpp://smppip');

router.get('/sendSMS', function(req, res, next) {
    var number = req.query.number;
    var message = req.query.message;
    console.log("number", number, "message", message)

    session.bind_transceiver({
        system_id: 'xx',
        password: 'xx'
    }, function(pdu) {
        console.log("- bind_transceiver pdu", pdu)
        if (pdu.command_status == 0) {
            // Successfully bound
            console.log("Successful bound!");
            session.submit_sm({
                source_addr: 'ABC',
                destination_addr: number,
                message_payload: message,
                source_addr_ton: 5,
                source_addr_npi: 1,
                dest_addr_ton: 1,
                dest_addr_npi: 1,
            }, function(pdu) {
                //console.log("- submit_sm pdu:", pdu)
                if (pdu.command_status == 0) {
                    console.log("- submit_sm success", pdu.message_id);
                    res.send({ errorCode: pdu.command_status, errorMessage: 'Send message success' });
                } else {
                    console.log("- submit_sm fail:", pdu);
                    res.send({ errorCode: pdu.command_status, errorMessage: 'Send message fail' });
                }
            });
        } else {
            console.log("Unsucessful Bound!");
            res.send({ error: pdu.command_status, success: 'Unsucessful Bound' });
        }
    });

});
`

**Comment by nimitwalia89** [comment]
My code runs without any errors. It gives response for message sent successfully. But no sms is received on device. Can i know what am i missing?

**Comment by juliangut** [comment]
This issue is too broad and too old, please if help is still needed open a new issue
