### ISSUE TITLE
Session doesn't emit error event (or any events) when connection breaks

### ISSUE THREAD

**Issue by notgiorgi** [farhadi/node-smpp#57]
Session doesn't emit error event (or any events) when connection breaks.

I run my app which basically does this:

- Starts session (successfully)
- Binds transciever (sccessfully)
- Sets timeout for `enquire_link`

After that I disconnect network, I continue enquiring link and submitting SMSes, it sends PDUs, doesn't receive any response, doesn't emit any error.

How can I detect network absence?

**Comment by Sukhrob** [comment]
You can do like this. But, you should use some kind of process control system like "http://supervisord.org/" in order to reconnect to an operator after process.exit(). Hope, it helps. Good luck!

    // Missed enquire links counter
    var counter = 0;

    // Total missed enquire links allowed
    var maxCount = 3;

    // Timeout for an enquire link
    var timeout = 20000; // 20 seconds

    var session = smpp.connect(
         'host',
         'port'
    );

    // Respond to an enquire link
    session.on('enquire_link', function (pdu) {
         session.send(pdu.response());
         logger.info('Responded an enquire link');
    });

    // Response to an enquire link
    session.on('enquire_link_resp', function (pdu) {
         counter = 0;
         logger.info('Received a response to an enquire link');
    });

    // Listen to the unbind event and kill the process
    session.on('unbind', function(pdu) {
         session.send(pdu.response());
         logger.info('SMPP unbind');
         session.close();
         process.exit();
    });

    // Kill the process on an SMPP connection error
    session.on('error', function (error) {
         logger.error('SMPP connection error: ' + error);
         session.close();
         process.exit(1);
    });

    // Kill the process when an SMPP connection is closed
    session.on('close', function () {
         logger.info('SMPP connection is closed');
         process.exit();
    });

    // Bind transceiver
    session.bind_transceiver({
         system_id: "your login",
         password: "your password"
    }, function (pdu) {
         if (pdu.command_status != smpp.errors.ESME_ROK) {
             logger.error('SMPP bind transceiver error: ' + pdu.command_status);
             session.close();
             process.exit(1);
         } else {
             logger.info('Connected');
             enquireLink();

             // Send sms here....
         }
    } 

    function enquireLink() {
        if (counter < maxCount) {
            session.enquire_link();
            counter++;
            logger.info('Enquired a link');

            setTimeout(function () {
                enquireLink();
            }, timeout);
        } else {
            logger.info('The SMPP connection is dead.');
            session.close();
            process.exit();
        }
    }
