### ISSUE TITLE
SMPP-Not able to send unicode message.

### ISSUE THREAD

**Issue by rajeshbn1989** [farhadi/node-smpp#59]
Hi @farhadi ,
   Need your help.
   I am trying to send uni code message from node.js using your library.
   I have set payload as :   
     var payload = {
            destination_addr: '919999999999',
            short_message: 'ರನ್!',
            source_addr: 'IM-DEMO',
            registered_delivery: '0',
            data_coding: 8,
        };
and submitting this payload.But unicode message is not properly sent to SMP3 server.It is receiving as some weird text.Please help.

**Comment by juliangut** [comment]
Hi @rajeshbn1989 I'm cleaning the repository, as your issue is 2 years old I don't know if you managed to fix it or not. I'm closing this issue, please open a new one if needed
