### ISSUE TITLE
Q: Do you need a plus sign on the validity period?

### ISSUE THREAD

**Issue by Arthur-W-White** [farhadi/node-smpp#62]
SMPPSim suggests you do:
[SMMPSim validity period parsing](https://github.com/haifzhan/SMPPSim/blob/master/src/main/java/com/seleniumsoftware/SMPPSim/pdu/SmppTime.java)

`logger.warning("SMPPSim currently only supports time component p=+. Value replaced with +");`

**Comment by juliangut** [comment]
Hi @Arthur-W-White 

The library supports time formats as described at the protocol

Encoding: https://github.com/farhadi/node-smpp/blob/master/lib/defs.js#L467

Decoding: https://github.com/farhadi/node-smpp/blob/master/lib/defs.js#L491

If you've found a bug please open an issue with more information
