### ISSUE TITLE
How do you use enquire link to maintain a connection with the server?

### ISSUE THREAD

**Issue by zehelvion** [farhadi/node-smpp#63]
I used this :
`                session.on('enquire_link', function(pdu) {
                        session.send(pdu.response());
                        console.log('.');
                });`
It looks like the callback is fired more and more times with each call...
Do I simply need to create one enquire link, calling it only once?

**Comment by sanjeevspr** [comment]
see sollowing article 
https://github.com/farhadi/node-smpp/issues/57

**Comment by juliangut** [comment]
Closing as question seems answered
