### ISSUE TITLE
Where DO I Need To Set Short Code 

### ISSUE THREAD

**Issue by HemanParbhakar** [farhadi/node-smpp#64]
Can You Please Help me Where we need to set short code

**Comment by ritmas** [comment]
I believe you have in mind sender value which is set as `source_addr`:

> session.submit_sm({
>    destination_addr: '<phone_number>',
>    source_addr: '<sender/shortcode>',
>    short_message: '<SMS_body>'
> });

**Comment by Heman6886** [comment]
var smpp = require('smpp');
var server = smpp.createServer(function(session) {
session.on('bind_transceiver', function(pdu) {
// we pause the session to prevent further incoming pdu events,
// untill we authorize the session with some async operation.
session.pause();
checkAsyncUserPass(pdu.system_id, pdu.password, function(err) {
if (err) {
session.send(pdu.response({
command_status: smpp.ESME_RBINDFAIL
}));
session.close();
return;
}
session.send(pdu.response());
session.resume();
});
});
});
server.listen(2775);

// Using This to create server please Hellp



Getting Error Of checkAsyncUserPass is not defined

**Comment by ritmas** [comment]
It's not clear in this code snippet whether you have defined such function `checkAsyncUserPass`

**Comment by Heman6886** [comment]
i have copy this fuction from README and there was exact the same

**Comment by ritmas** [comment]
This example is quite old and misleading. My suggestion is not to use `checkAsyncUserPass()` and do your own actions as successful `bind_transceiver` callback is all what you need - once it's fired up, you may send/receive messages.

**Comment by Heman6886** [comment]
ok Thankss And Can Transeceiver set to be multiple Connection at same time

**Comment by ritmas** [comment]
Well `transceiver` mode is dedicated for bidirectional communication, which means the same session supports both `transmitter` (sending messages) & `receiver` (receiving messages) modes. In other words, you don't have to initiate two connections at the same time to fully support communication with SMSC.

It's enough to maintain single session with SMSC for sending multiple messages and handling received ones at the same time. But if you want to handle multiple sessions to the same SMSC make sure SMSC configuration allows you to do that. In most cases, it should be restricted to 1-2 sessions only with different TPS, etc.

**Comment by Heman6886** [comment]
as My Connection is always open using node server.js . But At Same TIme How Can I Send Message

**Comment by ritmas** [comment]
It's given in `README` as an example, you need to use `session.submit_sm();`

**Comment by Heman6886** [comment]
but the sms number and message os dyanmic as it would be send by andorid

**Comment by Heman6886** [comment]
When I Get message Id that means Message has been Sent

**Comment by ritmas** [comment]
Not really. It means SMSC has accepted your request to send message. Later SMSC will notify you whether SMS has been successfully sent to user or not - that's delivery report. You should handle it upon received PDU with:
```
session.on('deliver_sm', function(pdu) {
   // parse/handle PDU
   session.send(pdu.response());
});
```
PDU example of deliveyr report is:
```
{
    command_length: 144,
    command_id: 5,
    command_status: 0,
    sequence_number: 33576672,
    command: 'deliver_sm',
    service_type: '',
    source_addr_ton: 1,
    source_addr_npi: 1,
    source_addr: '<phone>',
    dest_addr_ton: 2,
    dest_addr_npi: 1,
    destination_addr: '<schortcode>',
    esm_class: 4,
    protocol_id: 0,
    priority_flag: 0,
    schedule_delivery_time: '',
    validity_period: '',
    registered_delivery: 0,
    replace_if_present_flag: 0,
    data_coding: 0,
    sm_default_msg_id: 0,
    short_message: {
        message:'id:37bc0c3 sub:001 dlvrd:000 submit date:1705190504 done date:1705190504 stat:DELIVRD err:000'
    }
}
```
Here `stat:DELIVRD` indicates SMS has successfully reached destination.

**Comment by Heman6886** [comment]
Means i have to Implement this on Reciever

**Comment by MukitCSTE** [comment]
How to send 

SMSC --> ESME 

i mean can i work like this


session.deliver_sm({
	command_length: 144,
    command_id: 5,
    command_status: 0,
    sequence_number: 33576672,
    command: 'deliver_sm',
    service_type: '',
    source_addr_ton: 1,
    source_addr_npi: 1,
    source_addr: 'ElitBuzz SMPP Service',
    dest_addr_ton: 2,
    dest_addr_npi: 1,
    destination_addr: 'Client',
    esm_class: 4,
    protocol_id: 0,
    priority_flag: 0,
    schedule_delivery_time: '',
    validity_period: '',
    registered_delivery: 0,
    replace_if_present_flag: 0,
    data_coding: 0,
    sm_default_msg_id: 0,
    short_message: {
        message:'id:123 sub:001 dlvrd:000 submit date:1705190504 done date:1705190504 stat:DELIVRD err:000'
    }
	}, function(pdu) {
			if (pdu.command_status == 0) {
				// Message successfully sent
				
				console.log('The Delivary report  is  successfully sent');
			}
		});

**Comment by MukitCSTE** [comment]
session.deliver_sm it's working finally . Thanks to all :)

**Comment by Kindlysertir** [comment]
So, how can i does cuz i have this error : 

checkAsyncUserPass('wavesmpp1', 'wavesmp1', function(err) {
        ^

ReferenceError: checkAsyncUserPass is not defined
    at Session.<anonymous> (/root/smppserver.js:7:9)
    at emitOne (events.js:96:13)
    at Session.emit (events.js:188:7)
    at Session._extractPDUs (/root/node_modules/smpp/lib/smpp.js:67:8)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Socket.Readable.push (_stream_readable.js:134:10)

**Comment by Kindlysertir** [comment]
> `checkAsyncUserPass()` is custom function, you can define it by yourself:
> 
> ```js
> function checkAsyncUserPass(system_id, password, callback) {
>     if (system_id === 'wavesmpp1' && password === 'wavesmp1') {
>         callback(0); // no error
>     } else {
>         callback(1); // error
>     }
> }
> ```

Ok, thanks. But now i gat the error like : 

function checkAsyncUserPass(pdu.system_id, pdu.password, function(err) {
                               ^

SyntaxError: Unexpected token .
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by ritmas** [comment]
> function checkAsyncUserPass(pdu.system_id, pdu.password, function(err) {

You've defined function parameters as `pdu` object properties, but I assume you're passing them as `variables`. Double check on the code itself on how you're calling `checkAsyncUserPass()`.

**Comment by Kindlysertir** [comment]
I install smpp like : npm install smpp it work. Thanks !

**Comment by Kindlysertir** [comment]
But i can not connect to it.

**Comment by juliangut** [comment]
@Kindlysertir have you required the module in the code?

```node
var smpp = require('smpp');
```

**Comment by juliangut** [comment]
It's been almost 3 months since last answer, I assume we can close this issue. Feel free to comment again if needed
