### ISSUE TITLE
TLVs in _resp with non-zero command_status

### ISSUE THREAD

**Issue by latysheff** [farhadi/node-smpp#65]
According to SMPP documentation, tlvs may be returned in case of command failures, for example:
4.2.1.2 submit_sm_resp Syntax 
4.2.5 Message Submission Response TLVs 
The following table contains TLVs that can be returned in a submit_sm_resp or data_sm_resp PDU. All TLVs are relevant to transaction message mode only (ref. 4.2.10.4) 
...
**delivery_failure_reason** Include to indicate reason for delivery failure

current code prevents this
sadly, wireshark also doesn't dissect these parameters in _resps

**Comment by juliangut** [comment]
Please @latysheff can you point me to the point this TLVs are prevented to be read in submit_sm_resp? ar far as I know TLVs are checked on all PDUs

**Comment by latysheff** [comment]
Hi! OMG, 2 years. As far as I remember, by "current code prevents this" I have ment "prevents sending in resp", not reading.

**Comment by juliangut** [comment]
This was introduced in [this commit](https://github.com/farhadi/node-smpp/commit/0e8964b604e35a36e138e5f917233b3b2c180a57). According to SMPP protocol version 3.4 submit_sm_resp body should be empty but re-visioned protocol version 5 allowed TLV to be present on the body; as it seams not only for submit_sm_resp but for responses in general

Given each command is already composed based on defined parameters at `commands[command].params` it should be relatively easy to allow custom tlvs and leave the rest as is

**Comment by juliangut** [comment]
Please review PR #118 in which I reason why TLVs should not be allowed in error responses

If you consider I'm not correct feel free to comment on this ticket or the PR to reopen
