### ISSUE TITLE
How to send flash SMS using node smpp?

### ISSUE THREAD

**Issue by vermaslal** [farhadi/node-smpp#67]
Hi,

Is there any idea to send flash SMS using this module?

**Comment by ritmas** [comment]
If SMSC supports that, then yes. Usually it's enough to change message encoding, e.g.:
```
session.submit_sm({
   // 7bit alphabet
   data_coding: 0xF0
});
```

**Comment by vermaslal** [comment]
Thank you for quick reply. Using data_coding: 0xF0 solved my issue.
