### ISSUE TITLE
deliver_sm getting wrong encoded message content for ucs-2 SMS

### ISSUE THREAD

**Issue by vermaslal** [farhadi/node-smpp#68]
Hi,

I am using node-smpp@0.3.1 with node@v7.10.0

When I send ucs-2 message my server is giving me below delivery response
```�xxxxxxxxxxxxAlerts�id:S21311242091636504458661711 sub:001 dlvrd:001 submit date:170609163650 done date:170609163657 stat:DELIVRD err:000 text:```

but deliver_sm event is giving me below PDU
```
{
  command_length: 194,
  command_id: 5,
  command_status: 0,
  sequence_number: 0,
  command: 'deliver_sm',
  service_type: '',
  source_addr_ton: 0,
  source_addr_npi: 0,
  source_addr: 'xxxxxxxxxxxx',
  dest_addr_ton: 0,
  dest_addr_npi: 0,
  destination_addr: 'Alerts',
  esm_class: 4,
  protocol_id: 0,
  priority_flag: 0,
  schedule_delivery_time: '',
  validity_period: '',
  registered_delivery: 0,
  replace_if_present_flag: 0,
  data_coding: 8,
  sm_default_msg_id: 0,
  short_message: { message: '楤㩓㈱㌱ㄲ㐲〹ㄶ㌶㔰㐴㔸㘶ㄷㄱ⁳畢㨰〱汶牤㨰〱⁳畢浩琠摡瑥㨱㜰㘰㤱㘳㘵〠摯湥慴攺ㄷ〶〹ㄶ㌶㔷⁳瑡琺䑅䱉噒䐠敲爺〰〠瑥硴㨠†††††††††' } }
```
I will appreciate any help.

**Comment by jezeniel** [comment]
@vermaslal i know this might be late, are you using node's own `toString('ucs2')`?

**Comment by pardavib** [comment]
@vermaslal Try to remove all the other encodings at the beginning of your script:
`delete smpp.encodings.ASCII;
delete smpp.encodings.LATIN1;`

Also do not specify the `data coding` attribute when submitting the message.

This did the trick for me.

**Comment by juliangut** [comment]
Three years later is this still an issue @vermaslal ?

**Comment by juliangut** [comment]
No feedback for months, I'm closing this issue, feel free to reopen in needed

**Comment by tcort** [comment]
Trying to send `Café` gave me a similar issue. I tried sending with and without `data_coding` but it didn't work (the `é` was always missing on the handset or garbled (e.g. `Caf@@`). Following @pardavib's advice above, deleting ASCII and LATIN1 worked.
