### ISSUE TITLE
How to use the short_message object with UDH and message properties?

### ISSUE THREAD

**Issue by thjhmd** [farhadi/node-smpp#69]
Hi. I'm having trouble using UDH to concatenate the messages.
Can someone show me a simple example?
The below is what I have tried:

`
// begin
const config = require('../src/config.json');

var smpp = require('smpp');
var session = smpp.connect(config.smppSession);

smpp.encodings.default = 'UCS2';

session.bind_transceiver({
  system_id: config.systemId,
  password: config.systemPassword
}, (pdu) => {
  if (pdu.command_status === 0) {

    // here I try to send some messages
    session.submit_sm({
      source_addr: config.sourceAddress,
      destination_addr: config.destinationAddress,
      short_message: {
        udh: Buffer.from([0x05, 0x00, 0x03, 0x05, 0x02, 0x01]),
        message: "Hello World!"
      }
    }, (pdu) => {
      if (pdu.command_status === 0) {
        console.log("First OK");
      } else {
        console.log("First Error");
      }
    });

    // here's the second message I want to concatenate with
    // the first
    session.submit_sm({
      source_addr: config.sourceAddress,
      destination_addr: config.destinationAddress,
      short_message: {
        udh: Buffer.from([0x05, 0x00, 0x03, 0x05, 0x02, 0x02]),
        message: "Hello from Another World!"
      }
    }, (pdu) => {
      if (pdu.command_status === 0) {
        console.log("Second OK");
      } else {
        console.log("Second Error");
      }
    });

  }
});
// end
`

**Comment by ritmas** [comment]
Please define exact trouble you're having

**Comment by thjhmd** [comment]
Is it possible to use two submit_sm and concatenate both the messages with UDH?

**Comment by ritmas** [comment]
Yes, it's possible to use multiple `submit_sm`.
Is some error occurred while you were trying to submit SMS?

**Comment by thjhmd** [comment]
No, there were no errors and the messages were sent successfully but I wanted to send these two messages and then see them concatenated as one SMS message.

**Comment by thjhmd** [comment]
I've also tried message_payload property in place of short_message but I get no text in my SMS.
It becomes an empty text.

**Comment by ritmas** [comment]
Interesting. `short_message` with `udh` is the correct way, `udh` also looks composed correctly.
My suggestion is to try sending concatenated SMS in a sequence, not as separate `submit_sm`'s. I mean, as long Node.js is based on events, it could be that your code sends 2nd part of SMS faster than the 1st one. So give a try sending other SMS parts once `"First OK"` occurs.

If that does not solve the issue, try another thing - use randomly generated reference, not static `0x05`. Try this:
```
var concatRef = Math.floor(Math.random() * 255);
Buffer.from([0x05, 0x00, 0x03, concatRef, 0x02, 0x01])
```
instead of:
```
Buffer.from([0x05, 0x00, 0x03, 0x05, 0x02, 0x01])
```

**Comment by thjhmd** [comment]
```const config=require('../src/config.json');
var smpp=require('smpp');
var session=smpp.connect(config.smppSession);
session.bind_transceiver({
  system_id:config.systemId,
  password:config.systemPassword
},(pdu)=>{
  if(pdu.command_status!==0){
    console.log("failed");
  }else{
    var concatRef=Math.floor(Math.random()*255);
    let first_message=new Promise((resolve,reject)=>{
      session.submit_sm({
        source_addr:config.sourceAddress,
        destination_addr:config.destinationAddress,
        short_message:{
          udh:Buffer.from([0x05, 0x00, 0x03, concatRef, 0x02, 0x01]),
          message:"Hello World!"
        }
      },(pdu)=>{
        if(pdu.command_status!==0){
          reject("failed");
        }else{
          resolve("success");
        }
      });
    });

    let second_message=new Promise((resolve,reject)=>{
      session.submit_sm({
        source_addr:config.sourceAddress,
        destination_addr:config.destinationAddress,
        short_message:{
          udh:Buffer.from([0x05, 0x00, 0x03, concatRef, 0x02, 0x02]),
          message:"Hello from Another World!"
        }
      },(pdu)=>{
        if(pdu.command_status!==0){
          reject("failed");
        }else{
          resolve("success");
        }
      });
    });

    first_message
      .then((message)=>{
        console.log("first message was a "+message);
        return second_message;
      })
      .then((message)=>{
        console.log("second message was a "+message);
      })
      .catch((message)=>{
        console.log("everything "+message);
      });
  }
});
```

This is what I've tried but the messages still didn't concatenate.
Is it server side?

**Comment by ritmas** [comment]
Try this code snippet (that's what I'm using):
```
/* concatenate SMS */
var messages = [
        'Hello World!',
        'Hello from Another World!'
    ],
    concatRef = Math.floor(Math.random() * 255);
for (var i = 0; i < messages.length; i++) {
    var smsPart = messages[i],
        udh = new Buffer(6);
    udh.write(String.fromCharCode(0x5), 0); /* Length of UDH */
    udh.write(String.fromCharCode(0x0), 1); /* Indicator for concatenated message */
    udh.write(String.fromCharCode(0x3), 2); /* Subheader Length (3 bytes) */
    udh.write(String.fromCharCode(concatRef), 3); /* Same reference for all concatenated messages */
    udh.write(String.fromCharCode(messages.length), 4); /* Number of total messages in the split */
    udh.write(String.fromCharCode(i + 1), 5); /* Sequence number (used by the mobile to concatenate the split messages) */

    session.submit_sm({
        destination_addr: config.destinationAddress,
        source_addr: config.sourceAddress,
        short_message: {udh: udh, message: smsPart}
    }, function(pdu) {
        //
    });
}
```
If that does not resolve your issue, probably you need to debug on server side.

**Comment by thjhmd** [comment]
Hi,

Sorry that it's been a few days now. I've just now tried your code and it still didn't work.
I guess that it's something to do server side.
Thank you very much for your help and quick responses.

**Comment by thjhmd** [comment]
I've also got another problem regarding the encoding but should I open a separate issue for that?

**Comment by ritmas** [comment]
I'm sorry to hear that, but keep up digging :) You're welcome.

Regarding encoding, yeah, probably you need to create another issue unless it's solved already within the closed ones.

**Comment by thjhmd** [comment]
The error turned out to be server side. I'm not sure why and how it was fixed. Sorry.
I think some changes were made on server-connection.js file in this https://github.com/Roave/shorty in lib and that caused the issue with UDH messages.
After it was fixed, I could run your code.
Thanks!
