### ISSUE TITLE
Connect multiple clients to single server

### ISSUE THREAD

**Issue by sushant-kum** [farhadi/node-smpp#70]
How can i make multiple SMPP clients connect to single SMPP server process?

**Comment by abdelrahman-mustafa** [comment]
the straightforward guide is used for multiaple client for one server but don't use promises or async/await for server creation the session not returned after first created one

**Comment by juliangut** [comment]
Hello @sushant-kum 

Each bind connected client opens a socket connection to the server and it is handled asynchronously

If you want several processes you can use PM2 in cluster mode to handle connections to same port and hand them to the different processes

**Comment by juliangut** [comment]
It's been almost 3 months since last answer, I assume we can close this issue
