### ISSUE TITLE
How to  recombined Multi Part Messages  at the receiving end???

### ISSUE THREAD

**Issue by MukitCSTE** [farhadi/node-smpp#72]
Suppose a client send me a long multi part message using  udh. but how to parse this message in server side . Should i use like this one 

session.on('submit_sm', function(pdu) {
if(pdu.esm_class == 64 )

conslole.log('pdu.message_payload.message');

}

or i need to concatenated  manually parsing UDH. 

like 

Var parts_number = 'Number of pieces of the concatenated message from UDH '

for ( i= 0 . i<=parts_number , i++){
 // concatenating message parts here

message = message_parts[i]+ message ; 
}

**Comment by Ghost180195** [comment]
Hello. Have you been able to solve the problem?

**Comment by juliangut** [comment]
Hello @MukitCSTE and @Ghost180195 

The process on the receiving side should be done by the implementer, the library doesn't provide a means to do it, anyway UDH data has all you need to reconstruct the message

There are two types of Concatenated short messages UDH, 8-bit and 16-bit long https://en.wikipedia.org/wiki/User_Data_Header:

```
buffer = new Buffer([0x05,    0x00,   0x00,    0x4F,         0x02,         0x01]);
//                   length   IEI              messageId     parts count   part no.

buffer = new Buffer([0x06,    0x08,   0x0A,    0x20, 0x4F,   0x02,         0x01]);
//                   length   IEI              messageId     parts count   part no.
```

You should detect each part and combine them when they all arrive, mind that they can arrive in different order and nothing in the protocol says that the same part cannot be sent more than once

Hope this helps you

**Comment by juliangut** [comment]
It's been almost 3 months since last answer, I assume we can close this issue

**Comment by htmsl-techsupport** [comment]
I don't know if this is the best approach to concatenate messages in memory but this is how I did it.

`
//Global Vars
var userinfo = {};
userinfo.concatinate = {};

//Code inside submit_sm
let msgid = uuidv4();
if (
pdu.esm_class === smpp.consts.ESM_CLASS.UDH_INDICATOR ||
pdu.esm_class === smpp.consts.ESM_CLASS.KANNEL_UDH_INDICATOR
) {
// Mind that multiple UDH headers can arrive, here we read the first one
const udh = pdu.short_message.udh[0];

    if (udh[0] === 0x00 || udh[0] === 0x08) {
      let messageId = parseInt(udh[2]);
      let messageTotalParts = parseInt(udh[3]);
      let messagePart = parseInt(udh[4]);
      if (userinfo.concatinate.hasOwnProperty(messageId)) {
        userinfo.concatinate[messageId][messagePart - 1] = pdu;
        if (userinfo.concatinate[messageId].length == messageTotalParts) {
          let concatinatedMessage = '';
          userinfo.concatinate[messageId].forEach((concatPdu) => {
            concatinatedMessage += concatPdu.short_message.message;
          });
          delete userinfo.concatinate[messageId];
          pdu.short_message.message = concatinatedMessage;
        } else {
          //Sending message_id back to smpp client
          session.send(
            pdu.response({
              message_id: msgid,
            })
          );
          return;
        }
      } else {
        userinfo.concatinate[messageId] = [];
        userinfo.concatinate[messageId][messagePart - 1] = pdu;
        //Sending message_id back to smpp client
        session.send(
          pdu.response({
            message_id: msgid,
          })
        );
        return;
      }
    }
  }
`

**Comment by tapan-thapa** [comment]
Small improvement with javascript map.

```
if (udh[0] === 0x00 || udh[0] === 0x08) {
          let messageId = parseInt(udh[2]);
          let messageTotalParts = parseInt(udh[3]);
          let messagePart = parseInt(udh[4]);
          if (userinfo.concatinate.hasOwnProperty(messageId)) {
            userinfo.concatinate[messageId].set(messagePart - 1, pdu);
            if (userinfo.concatinate[messageId].size == messageTotalParts) {
              let concatinatedMessage = '';
              let concatinatedArray = [];
              for (const [key, value] of userinfo.concatinate[messageId]) {
                concatinatedArray[key] = value;
              }
              concatinatedArray.forEach((concatPdu) => {
                concatinatedMessage += concatPdu.short_message.message;
              });
              delete userinfo.concatinate[messageId];
              pdu.short_message.message = concatinatedMessage;
            } else {
              //Sending message_id back to smpp client
              session.send(
                pdu.response({
                  message_id: msgid,
                })
              );
              return;
            }
          } else {
            userinfo.concatinate[messageId] = new Map();
            userinfo.concatinate[messageId].set(messagePart - 1, pdu);
            //Sending message_id back to smpp client
            session.send(
              pdu.response({
                message_id: msgid,
              })
            );
            return;
          }
        }
```
