### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by Eomm** [farhadi/node-smpp#73]
Hi,
I would know if this project is alive and there is a feature-list that will be implemented.

I could contribute to improve some functions, but I see 5 PR not rejected or merged.

Thank you for your time

**Comment by ritmas** [comment]
I believe it's not dead, but project unrighteously attracts less attention than the other look-alike ones.

**Comment by juliangut** [comment]
Hello @Eomm and @ritmas I've recently been included in the project as a collaborator, lets hope for the project not to be dead :)
