### ISSUE TITLE
Binary SMS (ringtone, image, WML/WBXML)

### ISSUE THREAD

**Issue by ritmas** [farhadi/node-smpp#74]
What's needed for sending binary SMSs like ringtone, image or WML/WBXML to STK SIM?
Apart of using UDH and message concatenation, what else is needed? Some specific TLV parameters, DCS (data_coding), ESM class (esm_class)?

**Comment by ritmas** [comment]
Ok, let me share what I'm trying to do and what I've figured out at the moment..

As far as I understand, in order to send Wap Push Service Indication (SI) - one of binary message types - I need to have both proper plain XML and binary version (WBXML - WAP Binary XML) of SI. 
So based on OMA (Open Mobile Alliance) [SI specs/protocol](http://www.openmobilealliance.org/tech/affiliates/wap/wap-167-serviceind-20010731-a.pdf) for the plain XML part I came up with:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE si PUBLIC "-//WAPFORUM//DTD SI 1.0//EN" "http://www.wapforum.org/DTD/si.dtd">
<si>
    <indication href="http://example.com" action="signal-medium">This is test!</indication>
</si>
```
And converted it to WBXML as follows:
```    
    --# WSP #--
01 	This is Push Identifier
06 	WSP PDU Type = Push
04 	Length of octet followed 4 bytes
03 	Length of content-type + header (3 octets)
AE 	This is the content type of WAP Push (application/vnd.wap.sic)
81 	This is a header "Accept-Charset"
EA 	This is a value of header "Accept-Charset" which is UTF-8 (hexa code 0x6A) become 0xEA since 0xEA = 0x6A|0x80
    --# WBXML #--
02 	WBXML Version number 1.2
05 	SI 1.0 Public ID
6A 	Charset UTF-8
00 	String table length = 0 (constant)
45 	<si>
C6 	<indication>
0C 	href="http://
03 	String starts
6578616d706c65    example
00 	String ends
85      .com
07 	action="signal-medium"
01 	Ends of attributes, now the content
03 	String starts
54686973206973207465737421 	This is test!
00 	String ends
01 	</indication>
01 	</si>
```
In the end, result is:
```01060403AE81EA02056A0045C60C036578616d706c65008507010354686973206973207465737421000101```

Now, I need to send WBXML over SMPP:
```// UDH serves not only for SMS concatenation but also for setting UDHI
var udh = new Buffer(6);
udh.write(String.fromCharCode(0x5), 0); /* Length of UDH */
udh.write(String.fromCharCode(0x0), 1); /* Indicator for concatenated message */
udh.write(String.fromCharCode(0x3), 2); /* Subheader Length (3 bytes) */
udh.write(String.fromCharCode(Math.floor(Math.random() * 255)), 3); /* Same reference for all concatenated messages */
udh.write(String.fromCharCode(1), 4); /* Number of total messages in the split */
udh.write(String.fromCharCode(i + 1), 5); /* Sequence number (used by the mobile to concatenate the split messages) */

smpp.addTLV('source_port', smpp.tlvs.source_port);
smpp.addTLV('dest_port', smpp.tlvs.dest_port);

smpp.submit_sm({
    destination_addr: sms.msisdn,
    source_addr: sms.sender,
    short_message: {
        udh: udh,
        message: '01060403AE81EA02056A0045C60C036578616d706c65008507010354686973206973207465737421000101'
    },
    registered_delivery: smpp.consts.REGISTERED_DELIVERY.FINAL,
    source_addr_ton: smpp.consts.TON.INTERNATIONAL,
    source_addr_npi: smpp.consts.NPI.ISDN,
    dest_addr_ton: smpp.consts.TON.INTERNATIONAL,
    dest_addr_npi: smpp.consts.NPI.ISDN,
    data_coding: 0xF5,
    source_port: 9200,
    dest_port: 2948
}, function(pdu) {
    if (pdu.command_status !== smpp.ESME_ROK) {
        console.error('submit sms error:', pdu);
    }
});
```

Thing is that SMSC accepts `submit_sm` and no error arises, but user/ME (Mobile Equipment) does not see/show anything.
Clearly, there is something wrong, but which part?

- XML to WBXML convertion?
- WSP (Wireless Session Protocol) part should be defined somewhere else rather than at WBXML? Maybe in UDH? How?
- wrong TLV `source_port`/`dest_port` values?

**Comment by juliangut** [comment]
Hi @ritmas did you solved this? I'm afraid I cannot be of much help here

**Comment by ritmas** [comment]
No, it's still very relevant.

**Comment by juliangut** [comment]
Hi @ritmas searching a bit around this is what I've found so far

You should not be using TLVs for port addressing, you should do it in UDH as follows instead

```
06   | UDH length
05   | Application Port Addressing, 16 bit address
04   | Content length
0B84 | Destination port number, IANA WAP-push Multimedia Messaging Service port (2948)
0000 | Source port number
```

I guess you're not receiving any error from SMSC because normally when TLVs are not recognized they are plainly discarded, when SMSC wants to send the message it finds there is missing data

I don't know about WBXML stream, but binary data must be binary encoded and data_coding should go accordingly

```node
smpp.submit_sm({
    destination_addr: sms.msisdn,
    source_addr: sms.sender,
    short_message: {
        udh: Buffer.from([0x06, 0x05, 0x04, 0x0B, 0x84, 0x00, 0x00]),
        message: Buffer.from([0x01, 0x06, 0x04, 0x03, 0xAE, 0x81, 0xEA, 0x02, 0x05, 0x6A, 0x00, 0x45, 0xC6, 0x0C, 0x03, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x00, 0x85, 0x07, 0x01, 0x03, 0x54, 0x68, 0x69, 0x73, 0x20, 0x69, 0x73, 0x20, 0x74, 0x65, 0x73, 0x74, 0x21, 0x00, 0x01, 0x01'])
    },
    registered_delivery: smpp.consts.REGISTERED_DELIVERY.FINAL,
    source_addr_ton: smpp.consts.TON.INTERNATIONAL,
    source_addr_npi: smpp.consts.NPI.ISDN,
    dest_addr_ton: smpp.consts.TON.INTERNATIONAL,
    dest_addr_npi: smpp.consts.NPI.ISDN,
    data_coding: smpp.consts.ENCODING.BINARY
}, function(pdu) {
    if (pdu.command_status !== smpp.ESME_ROK) {
        console.error('submit sms error:', pdu);
    }
});
```

Have a look at this link which information I've used to write this comment: https://www.diafaan.com/manuals/diafaansmsserver/index.html?send_wap_push_message.html

Really hope this can help or can lead you in the right path

**Comment by juliangut** [comment]
@ritmas was of any use my last comment?

**Comment by bsmth** [comment]
@juliangut I can get your example working with a Service Indication.

**Comment by juliangut** [comment]
Hi @bsmth and thanks for your comment

Could you please explain what you mean by Service Indication?, so it stays here as documentation for anyone else wanting to send binary messages

**Comment by bsmth** [comment]
Ritmas' XML payload converted to WBXML contains a Service Indication (SI). @ritmas linked to the spec for this [in his comment]( https://github.com/farhadi/node-smpp/issues/74#issuecomment-392663118). 

This used to be a very common way to notify users of data service related events. A typical SI example is a WAP push that notifies the user of new emails or news events that the user is subscribed to. The use-case would be that the user is not connected to data services, but may still receive SMSs. This is really not used so much anymore now that data services are more affordable and prevalent, but can be useful for delivering notifications or instructions to set up data sessions correctly if they are misconfigured.

The following site has a good overview of a typical flow with some examples: https://adywicaksono.wordpress.com/2008/05/11/sending-wap-push-service-indication/

**Comment by juliangut** [comment]
Thanks so much @bsmth 

I'm closing this issue as it looks like the functionality is covered
