### ISSUE TITLE
TravisCL issue

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [farhadi/node-smpp#81]
Hi there, @farhadi 
There is something funny with the CL enviroment. Can you look at:
https://travis-ci.org/farhadi/node-smpp/jobs/395657897

**Comment by farhadi** [comment]
Hi,
This is an issue with tests when actual and expected values having a millisecond difference.
Its fixed in this pull request:
https://github.com/farhadi/node-smpp/pull/75

**Comment by Dragomir-Ivanov** [comment]
Thanks a lot. Closing.
