### ISSUE TITLE
Decoding with DCS = 0x0

### ISSUE THREAD

**Issue by shokuie** [farhadi/node-smpp#82]
folks,

My scenario, 
Device A (Apple) --> Sigtran --> Node SMPP (client mode) --> Carrier SMPP (server) --> Carrier Net --> Device B (Android)

Device A (Apple) sends GSM7 and message on Device B (Android) doesn't show correctly. So, I change the scenario as follows to debug. 

Device A --> Sigtran --> Node SMPP (Server mode) --> Node SMPP (client Mode) --> Consloe (Std Out)

When sending an SMS with DCS = 0x0 (GSM7) from Device A, the client automatically decodes it, so a wrong string format shows up, example :

Sent Buffer:
<Buffer c8 72 1e 94 3e bf e5 2c 50 7a 0e a2 a3 cb a0 b2 7b fc 26 a7 dd 67 d0 7b 0d 72 bf ef 3f>

Received String :
 rß >  ,PzÅ     ä &  g ä\rr  ?

If I disable decoder function on the client I receive exactly the same buffer, which is fine. Now, the question looks client does not recognize the DCS = 0x0 (GSM7) and decodes with something wrong. I think @farhadi 's code support ASCII only and not GSM7 (Encoding / Decoding), but to my surprise why it decodes DSC = 0 if it doesn't support GSM7.

I highly appreciate any help.

**Comment by Ghost180195** [comment]
I also receive text like you.
```
short_message:
   { udh: <Buffer 05 00 03 4c 02 01>,
     message: ' nPXNO  ePzÅ\n  o9ΘDG    ÆT    ä  ù A w \r  Asxy 6 Agy  Å   0\u001bD.   4  .    ΘDG A w  $  dP \r   eΔ L&   s=ö. Ae<  &  gΔ \r    vΘ     vY ß  ' } }
```

Have you been able to solve the problem?

**Comment by juliangut** [comment]
@shokuie could you answer?

**Comment by shokuie** [comment]
@Ghost180195 Let us know data_coding of the message and your scenario.

**Comment by juliangut** [comment]
After almost 6 months of inactivity on the issue I'm closing it. Comment again if you feel it's needed

**Comment by dotsinspace** [comment]
Facing the same...any suggestion...
