### ISSUE TITLE
Moving away from `new Buffer(...)`

### ISSUE THREAD

**Issue by gabrielschulhof** [farhadi/node-smpp#85]
`new Buffer(...)` is deprecated and unsafe. Would it be possible to use `Buffer.from(...)` instead, in [these places](https://github.com/farhadi/node-smpp/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22)?

**Comment by ritmas** [comment]
Yeah, created PR #95 for that.

**Comment by farhadi** [comment]
Fixed in https://github.com/farhadi/node-smpp/commit/e2b02d8603d8fa3d046f8292f94a1993d3f2c570!
