### ISSUE TITLE
Symbols instead of letters when receiving a large message

### ISSUE THREAD

**Issue by Ghost180195** [farhadi/node-smpp#86]
When I receive a message that has more than 160 latin characters, then the message is divided into parts and instead of letters I accept some characters. For example:
```
short_message:
   { udh: <Buffer 05 00 03 4c 02 01>,
     message: ' nPXNO  ePzÅ\n  o9ΘDG    ÆT    ä  ù A w \r  Asxy 6 Agy  Å   0\u001bD.   4  .    ΘDG A w  $  dP \r   eΔ L&   s=ö. Ae<  &  gΔ \r    vΘ     vY ß  ' } }
```

**Comment by Ghost180195** [comment]
@farhadi Can you help me with this question?

**Comment by juliangut** [comment]
I'm sorry but I don't understand, is this a question? a feature request?

**Comment by juliangut** [comment]
Duplicate of #82
