### ISSUE TITLE
Support for both SubmitSM and DeliverSM in the same TRx session

### ISSUE THREAD

**Issue by mlntdrv** [farhadi/node-smpp#88]
Hi,
Is it possible with the current implementation to have a TRx session with submits and delivers flying around in it? I'm having trouble figuring out how can a SMPP client start listening for delivers (besides sending submits) after it's bind_transceiver is accepted. Also, how can a SMPP server send delivers (besides listening for submits) in the same SMPP session after it has authorised it?
Can you provide examples please?
Regards,
Milan

**Comment by juliangut** [comment]
Hi @mlntdrv 

Current implementation in transceiver mode can both receive and submit PDUs once the bind is stablished and you receive a bind_transceiver_resp

I don't understand your question I'm afraid, by definition in transmitter once the bind is stablished you can listen for submits and then send those clients their delivers

Copying and extending from README:

```node
var smpp = require('smpp');
var server = smpp.createServer(function(session) {
	session.on('bind_transceiver', function(pdu) {
		session.pause();

		checkAsyncUserPass(pdu.system_id, pdu.password, function(err) {
			if (err) {
				session.send(pdu.response({
					command_status: smpp.ESME_RBINDFAIL
				}));
				session.close();
				return;
			}

            session.on('submit_sm', function(pdu) {
                // handle submit PDUs
            });

			session.send(pdu.response());
			session.resume();

            // handle deliver PDUs, i.e. extract them from a queue
		});
	});
});
server.listen(2775);
```

**Comment by juliangut** [comment]
It's been almost 3 months since last answer, I assume we can close this issue. Feel free to comment again if neede
