### ISSUE TITLE
set connect timeout

### ISSUE THREAD

**Issue by astutesoftware** [farhadi/node-smpp#89]
How to set a smpp connect timeout parameter?

**Comment by ritmas** [comment]
Why would you need a timeout? Can you give more details on that?

**Comment by astutesoftware** [comment]
For instance, I have about 200 different connections and do a health check as to which of those work and which of those don't work.
Since the time spent waiting for a non working connection is taking long, the whole health check routine takes a whole lot longer than the speed at which it can skip a non-responding connection using a timeout and moving ahead.

**Comment by astutesoftware** [comment]
I am doing a lookup over all the connections that i have for the following based on hostname,username,password,ip combinations and pull out a report that provides me intel on the following
1. Accounts that are accepting connections from anyip rather than being whitelisted to my corporate ip
2. has the provider locked me to fire out messages to a particular country prefix - allowing terminations to the whole world

Then i escalate to the providers to lock the account to an ip i specify/correct the routing. 
With a lot of connects, i run this as a weekly check and close loopholes if any aka security check.

What happens right now is if i have 100's of connects i do them serially and they get stuck waiting for the default timeout to happen, so the health check routine takes a looooong time. If i was able to set a custom timeout the routine would move on to the next host and finish out faster.

**Comment by ritmas** [comment]
Interesting. Can you share the routine-check code?
By the way, you can always prepare PR for timeout support.

**Comment by astutesoftware** [comment]
`var smpp = require('smpp');
var colors = require('colors');
var fs = require('fs');
var util = require('util');
var logFile = fs.createWriteStream('log.txt', { flags: 'a' });
  // Or 'w' to truncate the file every time the process starts.
var logStdout = process.stdout;
console.log = function () {
  logFile.write(util.format.apply(null, arguments) + '\n');
  logStdout.write(util.format.apply(null, arguments) + '\n');
}
console.error = console.log;

// //call remote url
// var sURL = "https://xxx.xxx.net/SysApi/gw_audit.php?server=all&crypt=no&token=axx#####";
// var request = require('request');
// request.get(sURL, function (error, response, body) {
//     if (!error && response.statusCode == 200) {
//         //var csv = body;
//         //console.log(body);
//         var json = JSON.parse(body);
//         console.log(json);

//         process.exit();
//         // Continue with your processing here.
//     }
// });



var fs = require('fs');
var iTotalServers;
var iDoneServers  = 0;
var session;
var arrVulnerable = [];

var arrServers = [];
 arrServers.push ({'hostname': 'xxx.xxx.net', 'port':'2345','username':'rrr','password':'xxxx'});

fs.readFile('sample.json', 'utf8', function(err, data) {  
    if (err) throw err;
    //console.log(data);
    json = JSON.parse(data);
    console.log(json.int.length);
    var ilength = json.int.length;
    //ilength =2;
    for(i=0;i<ilength;i++)
    {
    	var hostname = json.int[i].ip;
    	var username = json.int[i].gwuser;
    	var password = json.int[i].gwpass;
    	var port = json.int[i].port;
    	if(lastChar = hostname[hostname.length -1]==="x")
    	{
    		console.log(hostname);
    	}
    	else
    	{
    		arrServers.push ({'hostname': hostname, 'port': port,'username':username,'password':password});

    	}
    	//console.log("last char:" + )

    	
    }
     iTotalServers = arrServers.length;
     iTotalServers=1;
    doCheck();
    //console.log(arrServers);

});




// ashsih - sTransreceiver mode


var doCheck = function()
{
	//check the credentials
	var sHostName = arrServers[iDoneServers].hostname;
	var sUsername = arrServers[iDoneServers].username;
	var sPassword = arrServers[iDoneServers].password;

	console.log("Scrutinizing " + sUsername + "@" + sHostName);


session = smpp.connect('smpp://' + arrServers[iDoneServers].hostname + ':' + arrServers[iDoneServers].port, function(e)
{

});

session.on('error', function(error){
  //console.log('smpp error', error)
  didConnect = false;
  session.close(function (){
        	//console.log("SESSION TERMINATED".yellow);
        	
        });
  if(error.code==="ETIMEDOUT" || error.code==="ECONNRESET")
  {
  	var errString = arrServers[iDoneServers].username + "@" + arrServers[iDoneServers].hostname + " is safe/TIMEOUT";
  	console.log(errString.green);
  	doNext();
  }
  else
  {
  	console.log(error.code);
  	doNext();
  }

})
session.bind_transceiver({
    system_id: arrServers[iDoneServers].username,
    password: arrServers[iDoneServers].password
}, function(pdu, systemid=arrServers[iDoneServers].username, password="yy") {
  //console.log(pdu);
  console.log("systemid" + systemid);
	//console.log("PDU STATUS:" + pdu.command_status);
    if (pdu.command_status == 0) {
        // Successfully bound
        //console.log(pdu);
        var errString = arrServers[iDoneServers].username + "@" + arrServers[iDoneServers].hostname + " is unsafe";
        console.log(errString.red);
        //arrVulnerable.push[]
        session.close(function (){
        	console.log("SESSION TERMINATED".yellow);
        	doNext();
        });
        session.submit_sm({
            destination_addr: '+919820329193',
            short_message: 'vulnerability check - MK'
        }, function(pdu) {
            if (pdu.command_status == 0) {
                // Message successfully sent
                console.log(pdu.message_id);
            }
        });
    }
    else
    {

    	console.log("FOUND NEW PDU STATUS" + pdu.command_status);
    	console.log(pdu);
    	doNext();
    }
});


}


var doNext = function()
{

	iDoneServers++;

	if(iDoneServers===iTotalServers)
	{
		//job complete
		console.log ("Job Complete")
	}
	else
	{

		doCheck();
	}

}






`

**Comment by ritmas** [comment]
From the code you've shared above, I'd suggest you to run routine-check in asynchronous way, not opposite. Now you read a config file and run checks in sequential way as:
```js
fs.readFile('sample.json', 'utf8', function (err, data) {
    json = JSON.parse(data);
    var ilength = json.int.length;
    for (i = 0; i < ilength; i++) {
        arrServers.push({
            'hostname': json.int[i].ip,
            'port': json.int[i].port,
            'username': json.int[i].gwuser,
            'password': json.int[i].gwpass
        });
    }
    doCheck(); // <== var arrServers used inside, server by server
});
```
which could be refactored as:
```js
fs.readFile('sample.json', 'utf8', function (err, data) {
    json = JSON.parse(data);
    var ilength = json.int.length;
    for (i = 0; i < ilength; i++) {
        // initiate connection to all servers and update each status asynchronously
        doCheck({
            'hostname': json.int[i].ip,
            'port': json.int[i].port,
            'username': json.int[i].gwuser,
            'password': json.int[i].gwpass
        });
    }
});
```

By the way, do you have all those servers binded/connected 24/7 already and this routine-check is just on top of that? If yes, please consider the fact SMPP server might forbid establishing more than 1 connection per user/credentials, depending on business logic.
So if that's the case, personally I would monitor socket on existing connection, next to app logic.

**Comment by juliangut** [comment]
@astutesoftware did you find last comment useful?

**Comment by juliangut** [comment]
It's been almost 3 months since last answer, I assume we can close this issue. Feel free to comment again if neede
