### ISSUE TITLE
GSM Shift tables

### ISSUE THREAD

**Issue by juliangut** [farhadi/node-smpp#91]
I see "filters.message" encode/decode does not consider UDH for shift tables, does anyone know how to easily implement them with the library?

If not @farhadi would you happily accept a PR to support them? by extending "encodings.ASCII" to accept UDH or adding new encodings?

Update: I've just seen #52 which should be merged in case of the mentioned PR is created

**Comment by juliangut** [comment]
Hello @farhadi 

Don't know if you've had time to review PR #100 but from my side I'm in a little of a hurry to have shift tables implemented so I'm going to need to fork the project if I don't get any feedback on whether you see it fit or not.

There are other interesting PR and issues that need some attention and love as well

**Comment by farhadi** [comment]
Hi @juliangut,
Thanks for the PR! I just merged it.
Unfortunately I didn't have enough time to maintain this project.
May I add you as a collaborator so that you can help me on keeping this project updated?

**Comment by juliangut** [comment]
Hi @farhadi firstly thanks for the merge, secondly this project plays an important part in the company I work for so I'd be more than happy to be able to help

**Comment by farhadi** [comment]
@juliangut I just added you as collaborator.
Thanks again!
