### ISSUE TITLE
how do I get remote ip in server scenario

### ISSUE THREAD

**Issue by yurunhub** [farhadi/node-smpp#92]
I am trying to get remote ip authentication working along with system_id/password but can't get remote ip anywhere for server scenario.
Thanks for your project and kind help.

**Comment by ritmas** [comment]
Can you precise your request? Do you want to test client-server integration but don't have any up & running server?

**Comment by alexeevdv** [comment]
https://www.npmjs.com/package/ipaddr.js/v/1.1.0

```js
let smpp = require('smpp');
let ipaddr = require('ipaddr.js');

smpp.createServer(function (session) {
    let clientIP = ipaddr.process(session.options.socket.remoteAddress).toString();
    // here you can make ip authentication
}
```

**Comment by juliangut** [comment]
This issue seems answered, feel free to reopen if needed
